### ISSUE TITLE
Mobile Enhancements

### ISSUE THREAD

**Issue by Teena126** [hngprojects/hng_boilerplate_nextjs#1034]
### Description

Description:
Activate roles and permission on user actions.

### Acceptance Criteria

• Users can only perform actions that are explicitly permitted by their assigned roles.
• Ensure that each role (e.g., Admin, user, Guest) has a predefined set of actions they are authorized to perform.

### Links

| [`FIGMA LINK`](LINK_HERE)

### Images

![image](URL_HERE)

**Comment by phoenixdahdev** [comment]
explain what is to be done in details

**Comment by Teena126** [comment]
The user should be able to switch organizations for eg if you are using Slack you can switch from hng to another organization  Sent from Mail for Windows From: James Ayomikun AraoyeSent: Wednesday, August 21, 2024 8:59 PMTo: hngprojects/hng_boilerplate_nextjsCc: Teena126; AuthorSubject: Re: [hngprojects/hng_boilerplate_nextjs] Mobile Enhancements (Issue #1034) explain what is to be done in details—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***> Virus-free.www.avast.com
