### ISSUE TITLE
' Enhancement' Implement Organization switch functionality between user and organizations.

### ISSUE THREAD

**Issue by Teena126** [hngprojects/hng_boilerplate_nextjs#1035]
### Description

Descriptions:
 To allow users to seamlessly switch between their personal accounts and any organizations they are a part of within the application.

### Acceptance Criteria

• The switch should be accessible from the main navigation or account settings menu.

### Links

| [`FIGMA LINK`](LINK_HERE)

### Images

![image](URL_HERE)

**Comment by phoenixdahdev** [comment]
please be very precise
