### ISSUE TITLE
[Bug]:  "Already have an account? Login" Link Not Redirecting to Login Page

### ISSUE THREAD

**Issue by Peterakabs** [hngprojects/hng_boilerplate_nextjs#1048]
### Description

The "Already have an account? Login " link on the Create Organization page is not functioning correctly. When clicked, it should redirect users to the Login page, but instead, it remains on the Create Organization page.

### Acceptance Criteria

The "Already have an account? Login " link redirects users to the Login page

### Links

| [`FIGMA LINK`](LINK_HERE)
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=1-2&t=Sg3zZQbvw4wy66zH-0

### Images

![image](URL_HERE)

**Comment by seshto13** [comment]
I will work on this
