### ISSUE TITLE
[Bug]  Invite Link Visibility Based on Toggle State in Members Settings Page

### ISSUE THREAD

**Issue by Zaraorji** [hngprojects/hng_boilerplate_nextjs#1051]
### Description

Currently,  in the UI for Members Settings Page, for inviting new members,  where the invite link is visible even when the toggle switch is not active. The expected behavior is that the invite link should only be visible when the toggle switch is enabled

## User Story
As a user, I want the invite link to be hidden when the toggle is disabled and visible only when the toggle is enabled so that the interface behaves consistently with the toggle state.

## Requirements:
1. When the toggle switch is  disabled, The invite link field and "Copy link" button should not be displayed.
2. When the toggle switch is  enabled, The invite link field and "Copy link" button should be displayed.
3. The toggle should control the visibility of the invite link in real-time without requiring a page refresh.

### Acceptance Criteria

- Given that the toggle is disabled, when the user views the invite link section, then the invite link field and "Copy link" button should not be visible.
- Given that the toggle is enabled,  when the user views the invite link section, then the invite link field and "Copy link" button should be visible.
- Given that the toggle is disabled when the user interacts with the toggle, then the invite link field and "Copy link" button should immediately disappear.
- Given that the toggle is enabled when the user interacts with the toggle, then the invite link field and "Copy link" button should immediately appear.

### Links

| [`FIGMA LINK`](LINK_HERE)
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=11001-63589&m=dev

### Images

![image](URL_HERE)
![Screen Shot 2024-08-21 at 10 52 18 PM](https://github.com/user-attachments/assets/c9bb6579-6589-46a9-a903-062da7c5d8f6)
Wrong implementation

![Screen Shot 2024-08-21 at 10 52 44 PM](https://github.com/user-attachments/assets/b22da27c-70e2-4430-8d0a-c4470569ad7f)
Figma screenshot, what it should be like

**Comment by seshto13** [comment]
I will work on this

**Comment by Chioma227** [comment]
Is this done with? @seshto13

**Comment by Chioma227** [comment]
This issue has been fixed.
