### ISSUE TITLE
[BUG]: Wrong Placeholder text name for password 

### ISSUE THREAD

**Issue by CoreyOdonis** [hngprojects/hng_boilerplate_nextjs#1058]
### Description

when a user tries sign up on the HNG boilerplate with their details (first name, last name, email and password), in the password field, the placeholder text provided is "register.passwordplaceholder"

This issue is Frontend related

### Acceptance Criteria

The password placeholder text should say "Enter Password" 

### Links

| [`LIVE LINK`](https://kimiko-csharp.teams.hng.tech/register)

### Images

![Wrong password placeholder text](https://github.com/user-attachments/assets/94ac8794-f3ba-41ab-9c33-a78b31479254)

**Comment by Muneerat** [comment]
Working on this
