### ISSUE TITLE
[BUG]: Highlighted "Go to plans" text in the members page isn't clickable 

### ISSUE THREAD

**Issue by CoreyOdonis** [hngprojects/hng_boilerplate_nextjs#1068]
### Description

The "Go to plans" text under manage members found under settings page should take users to the current plan page when clicked but currently, It isn't clickable.

This is a frontend issue

### Acceptance Criteria

- Parse in the relevant hyperlink that will take the user to the plans page when they click on the "Go to plans" text

### Links

| [`LIVE LINK`](https://kimiko-csharp.teams.hng.tech/dashboard/admin/settings/organization/members)

### Images

![Go to plans link not clickable](https://github.com/user-attachments/assets/dfd9970e-8387-4d1e-ac26-54f2ee14ca41)

**Comment by Muneerat** [comment]
Working on this
