### ISSUE TITLE
[FIX): Update Invite Members Modal with Correct Title and Role Dropdown

### ISSUE THREAD

**Issue by Zaraorji** [hngprojects/hng_boilerplate_nextjs#1071]
### Description

In the invite members modal, the title should display as "Invite to [organization name]'s organization." Additionally, the dropdown should allow users to select a role within the organization, not a list of organizations.

##Requirements:
1. Update the modal title to say "Invite to [organization name]'s organization," where [organization name] is dynamically filled with the name of the current organization.
2. Change the dropdown menu to "select role"  instead of showing  "list of organizations".

### Acceptance Criteria

The title of the invite members modal should correctly show "Invite to [organization name]'s organization."
The dropdown should allow users to select the role of the new member within the organization, not show a list of organizations.

###Expected Outcome:
The invite members modal should have the correct title and a dropdown that allows selection of roles within the organization.

### Links

| [`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=21484-15710&m=dev)

### Images

![image](URL_HERE)

**Comment by Zaraorji** [comment]
![Screen Shot 2024-08-22 at 3 36 05 AM](https://github.com/user-attachments/assets/28f377c1-d9ca-4d1a-8dfe-f11655c11186)
![Screen Shot 2024-08-22 at 3 35 14 AM](https://github.com/user-attachments/assets/c859a222-d864-4114-9723-54fb3158f74d)

**Comment by Muneerat** [comment]
Working on this

**Comment by Zaraorji** [comment]
> Working on this

@Muneerat please are you done working on this?

**Comment by Muneerat** [comment]
Yes
