### ISSUE TITLE
[FEATURE] Create Switch Input Box

### ISSUE THREAD

**Issue by judeb21** [hngprojects/hng_boilerplate_nextjs#108]
## Description
Develop a switch input component. This component must maintain all states according to design. This switch component should be visually appealing as well as functional. It will be used across all pages.

## Acceptance Criteria

- Switch Input Component should be implemented according to the design [Guideline](https://ui.shadcn.com/docs/components/switch)
- Write test to assert functionality
- The component must be functional, it will be used across all pages

### Requirements

- [ ] Ensure UI consistency
- [ ] Ensure Component can receive prop values
- [ ] Ensure component can emit prop values to where needed
- [ ] Develop component according to the design

### Testing

- Ensure UI consistency
- Ensure component receives props and is able to read props
- Ensure component can emit values to components needed

### Link
[Figma link](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=2225-8100&m=dev)

### Image
<img width="143" alt="Screenshot 2024-07-17 at 17 18 34" src="https://github.com/user-attachments/assets/986ba70a-65fd-405b-9b13-cc5d241a8239">

**Comment by danthecm** [comment]
@judeb21 This is too small to be an issue, it should be merged into a similar issue
