### ISSUE TITLE
[Fix]: Update Placeholder Text in Pronouns Dropdown Field

### ISSUE THREAD

**Issue by Zaraorji** [hngprojects/hng_boilerplate_nextjs#1086]
### Description

Update the placeholder text in the Pronouns dropdown input field in the Profile General Settings to correctly display "Select" instead of "Select Language."

###Requirements:
1. Change the placeholder text in the Pronouns dropdown field to "Select."

### Acceptance Criteria
1. The Pronouns dropdown input field displays "Select" as the placeholder text.
3. No other functionality or design elements are affected.

###Expected Outcome:
1. Users see "Select" as the placeholder text in the Pronouns dropdown input field.
2. The dropdown field is fully functional and adheres to the design specifications provided in Figma.

### Links

| [`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=10-16358&m=dev)

### Images

![image](URL_HERE)

**Comment by Zaraorji** [comment]
![Screen Shot 2024-08-22 at 3 15 47 AM](https://github.com/user-attachments/assets/87326cbd-68c7-4184-a740-98926768ad96)
![Screen Shot 2024-08-22 at 3 16 23 AM](https://github.com/user-attachments/assets/99bc9c63-0b35-4391-a46f-c07b06ba1b8c)

**Comment by Muneerat** [comment]
Working on this
