### ISSUE TITLE
[Bug]: Remove "Compare All Features" Text from Payment Information Page

### ISSUE THREAD

**Issue by Peterakabs** [hngprojects/hng_boilerplate_nextjs#1109]
### Description

Remove the "Compare All Features" text from the footer of the Payment Information page, as it is confusing and not relevant to the payment process. It is easily confused as a link and the user already sees the payments plan highlights, so having compare all features there is confusing.

### Acceptance Criteria

- The "Compare All Features" text is no longer visible on the Payment Information page
- The footer only contains relevant text and information for the payment process

### Links

| [`FIGMA LINK`](LINK_HERE)
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=10-16358&t=fGqj98cF3No0d7as-0

### Images

![Screenshot (225)](https://github.com/user-attachments/assets/dc88b5b6-37f2-482b-8bbd-a839b6eacd01)

**Comment by Chioma227** [comment]
I will work on this.

**Comment by Chioma227** [comment]
Done.
