### ISSUE TITLE
[BUG]: Back Arrow on Settings side menu bar not clickable

### ISSUE THREAD

**Issue by delight-xxx** [hngprojects/hng_boilerplate_nextjs#1128]
### Description

On the side nav bar, the user should be able to go back to the previous page.

### Acceptance Criteria

1. The back button when clicked redirects the user to the previous page.
2. The back button on the side navigation bar is fully clickable and functional.
3.  The back button correctly navigates to the previous page or section as intended.
4.  Visual feedback is provided when the back button is hovered over or clicked.
5.  The back button works consistently across different devices, screen sizes, and browsers.
6.  The back button is accessible via keyboard navigation and screen readers.

### Expected Outcome:
The back button on the side navigation bar is fully functional, providing users with an easy and reliable way to navigate back to the previous page or section.

### Links

| [`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=24434-47394&t=NFtHhOdRKx2Uw88K-1)
<img width="320" alt="Screenshot 2024-08-22 at 9 28 27 AM" src="https://github.com/user-attachments/assets/edb933a5-5b3e-48c7-a750-3d13b33fbb57">
<img width="1090" alt="Screenshot 2024-08-23 at 1 25 20 AM" src="https://github.com/user-attachments/assets/306edebf-0ffc-446f-8bdf-7468ca424d2d">

### Images

![image](URL_HERE)

**Comment by Feng-09** [comment]
I will work on this
