### ISSUE TITLE
[FEATURE] Create and implement the API integration for Related Articles on the dynamic blog page

### ISSUE THREAD

**Issue by taiwonaf** [hngprojects/hng_boilerplate_nextjs#113]
# **Description**
Implement the design for the related articles, make it responsive on both the web and mobile screens. Make use of reusable components for the related ariticles. Integrate the api to map out the all related articles in the blog details page

# **Acceptance Criteria**
- Pixel perfect implementaiton
- Responsive implementation
- Clean code
- Make use of reusable components where needed, make one if needed
- Follow the [contribution guidelines](https://github.com/hngprojects/hng_boilerplate_nextjs/blob/0acf613964ea064ae211a91d0a74d13938e4bc23/CONTRIBUTING.md) and [code of conduct](https://github.com/hngprojects/hng_boilerplate_nextjs/blob/0acf613964ea064ae211a91d0a74d13938e4bc23/CODE_OF_CONDUCT.md)

# **Requirements**
- Display three related articles
- Proper error handling
- Proper loading indicator
- None breaking api integration

# **Testing**
- Write test to ensure the page renders the required contents

# **Deadline**
Friday 11:59 pm WAT

# **Tasks**
- [ ] Implement all the sections in the design
- [ ] Responsiveness across all screens
- [ ] Make use of reusable components where needed
- [ ] Write test for the implementations
- [ ] Proper commit message

# **Images**
![Frame 53126](https://github.com/user-attachments/assets/56ce1b5d-42eb-434c-8f9d-e1069661f6c8)
![Frame 1171275100](https://github.com/user-attachments/assets/138a52b3-2036-4362-a1f9-8873de725184)

[Figma design](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=1632-11446&m=dev)

**Comment by Kored28** [comment]
Please where can I find the API

**Comment by taiwonaf** [comment]
Ignore the api

**Comment by Kored28** [comment]
okay thank you

**Comment by taiwonaf** [comment]
> okay thank you

Use dummy data for now

**Comment by Kored28** [comment]
done with the implementation and testing of the arcticle component.  What should I do next?

**Comment by taiwonaf** [comment]
> done with the implementation and testing of the arcticle component. What should I do next?

follow [Contribution guideline](https://github.com/hngprojects/hng_boilerplate_nextjs/blob/c95eeba04d92cfc51ac5daa54787f54517e45c78/CONTRIBUTING.md) and make a pr to dev
