### ISSUE TITLE
[FEAT] External Dynamic Pages > Career Page > Implement no Available jobs

### ISSUE THREAD

**Issue by kleenpulse** [hngprojects/hng_boilerplate_nextjs#114]
## Description
Develop a component to display when no job listings matches the user's search criteria. This component should provide clear feedback and guidance to users.

## Acceptance Criteria

- The component displays an appropriate illustration and message when no jobs are available.
- The component is responsive and displays correctly on all screen sizes.
- The message is clear and provides helpful next steps for the user.

### Requirements	
The "no available jobs" component should include:
- An illustrative graphic representing the absence of available jobs.
- A primary message indicating no jobs available.
- A secondary message encouraging users to try again later

### Tests

- Verify that the component displays correctly when no jobs are found.
- Test the responsiveness of the component across various device sizes.

###  Tasks

- Design the "no available jobs" component based on the provided example and requirements.
- source an appropriate illustrative graphic
- Write the primary and secondary messages, focusing on clarity and user guidance.
- Implement any animations or transitions for smooth appearance/disappearance of the component.

# LINKS

[`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=1553-43135&m=dev).

# IMAGES

![image](https://github.com/user-attachments/assets/ca7a849f-6def-4a11-af24-15fa116d566e)

**Comment by danthecm** [comment]
Duplicate: 
https://github.com/hngprojects/hng_boilerplate_nextjs/issues/119
