### ISSUE TITLE
[Feature]: [Bug] Font Sizes on Blog Titles Not Consistent

### ISSUE THREAD

**Issue by Benjam1n7** [hngprojects/hng_boilerplate_nextjs#1145]
### Description

The font sizes of blog titles do not match the sizes specified in the Figma design.

### Acceptance Criteria

Steps to Reproduce:

View blog titles.
Compare font sizes with Figma design.
Expected Behavior:
Font sizes should align with the design specifications.

Actual Behavior:
Font sizes are inconsistent.

### Links

| [`FIGMA LINK`](LINK_HERE)
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=3-11896&t=tfPuhDGkOXgqSyLI-1

### Images

![image](URL_HERE)

**Comment by Praizee** [comment]
I'll work on this.

**Comment by Praizee** [comment]
@Benjam1n7 
This isn't the right figma link
Also, the screenshot you attached is broken

**Comment by Benjam1n7** [comment]
Bug seems to be fixed
