### ISSUE TITLE
[Feature]: [Bug] Card Background Colors Not Matching Design

### ISSUE THREAD

**Issue by Benjam1n7** [hngprojects/hng_boilerplate_nextjs#1149]
### Description

Card background colors do not match the colors specified in the Figma design.

### Acceptance Criteria

Steps to Reproduce:

View card elements.
Compare background colors with Figma design.
Expected Behavior:
Card background colors should match the design.

Actual Behavior:
Background colors are inconsistent.

### Links

| [`FIGMA LINK`](LINK_HERE)
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=3-11896&t=tfPuhDGkOXgqSyLI-1

### Images

![image](URL_HERE)

**Comment by seshto13** [comment]
I will work on this

**Comment by seshto13** [comment]
What background are you talking about, the figma link is not linking to any card. More information is needed on this.

**Comment by Benjam1n7** [comment]
Sorry, wrong ticket cos its not same with what i have on my drafts
