### ISSUE TITLE
[Feature]: [Enhancement] Add Loading Spinner for Data Fetching

### ISSUE THREAD

**Issue by Benjam1n7** [hngprojects/hng_boilerplate_nextjs#1152]
### Description

Include a loading spinner for data fetching operations to improve user feedback.

### Acceptance Criteria

Provides visual feedback during data loading processes

### Links

| [`FIGMA LINK`](LINK_HERE)
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=3-11896&t=tfPuhDGkOXgqSyLI-1

### Images

![image](URL_HERE)

**Comment by Bright-Abel** [comment]
Kindly provide a live link and a picture..
