### ISSUE TITLE
[Enhancement]: [Anchor FE]  Improve Career Page for When "No Jobs are Available"

### ISSUE THREAD

**Issue by FUUREsama** [hngprojects/hng_boilerplate_nextjs#1180]
### Description

Enhance the display when there are no job listings available by providing engaging placeholder content and making the "No available Jobs at the moment. Come back later!" message clickable. This content could include options for users to subscribe to newsletters, visit the company blog, or learn more about the company through videos or achievements in "about us".

### Acceptance Criteria

- All buttons and links in the placeholder content are clickable and functional.
- The design and layout are consistent with the rest of the career page.

### Links

| [`FIGMA LINK`](LINK_HERE)

### Images

![image](https://github.com/user-attachments/assets/b41b314f-7ad0-46f7-91d1-a20887fc9fda)

**Comment by Adufe-Obanijesu** [comment]
I am working on this
