### ISSUE TITLE
[Bug]: Remove Duplicate "Contact Us" Link on Help Center Page

### ISSUE THREAD

**Issue by Peterakabs** [hngprojects/hng_boilerplate_nextjs#1187]
### Description

The Help Center page currently has two separate "Contact Us" links, one under "We couldn't answer your question" and another under "Didn't find an answer". Remove the link under "We couldn't answer your question" to avoid duplication and improve user experience.

User Story:
As a user, I want a single, prominent "Contact Us" link on the Help Center page, making it easy to get in touch with support when I need help.

Requirements:

- Remove the "Contact Us" link under "We couldn't answer your question"
- Leave the "Contact Us" link under "Didn't find an answer" intact

### Acceptance Criteria

- The "Contact Us" link under "We couldn't answer your question" is removed
- The "Contact Us" link under "Didn't find an answer" remains and is functional

### Links

| [`FIGMA LINK`](LINK_HERE)
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=10-16358&t=TDcd6U4WQyAaScvP-0

### Images

![Screenshot (230)](https://github.com/user-attachments/assets/3e20c2b5-26f3-46d7-9ba7-62b58a3fe8c1)

**Comment by Chioma227** [comment]
I will work on this.

**Comment by Chioma227** [comment]
Done.
