### ISSUE TITLE
[Bug]: Fix Privacy Policy Link in Footer to lead Users to Correct Destination

### ISSUE THREAD

**Issue by Peterakabs** [hngprojects/hng_boilerplate_nextjs#1189]
### Description

The "Privacy Policy" link in the footer currently redirects users to the home page instead of the actual Privacy Policy page. Update the link to direct users to the correct page.

User Story:
As a user, I expect the "Privacy Policy" link in the footer to take me directly to the Privacy Policy page, so I can easily access and review the policy.

Requirements:

- Identify the incorrect link in the footer
- Update the link to point to the correct Privacy Policy page URL
- Test the link to ensure it directs users to the correct page

### Acceptance Criteria

- The "Privacy Policy" link in the footer directs users to the correct Privacy Policy page
- The link is functional and works as expected

### Links

| [`FIGMA LINK`](LINK_HERE)
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=10-16358&t=5674AcOi1CIMUzZJ-0

### Images

![image](https://github.com/user-attachments/assets/91acd877-1fef-4b86-a555-b98fc73dce68)

**Comment by Chioma227** [comment]
I will work on this

**Comment by Chioma227** [comment]
Done
