### ISSUE TITLE
[Bug]: Fix Terms of Use Link in Footer to Lead Users to the Correct Destination

### ISSUE THREAD

**Issue by Peterakabs** [hngprojects/hng_boilerplate_nextjs#1190]
### Description

The "Terms of Use" link in the footer currently redirects users to the home page instead of the actual Terms of Use page. Update the link to direct users to the correct page.

User Story:
As a user, I expect the "Terms of Use" link in the footer to take me directly to the Terms of Use page, so I can easily access and review the terms.

Requirements:

- Identify the incorrect link in the footer
- Update the link to point to the correct Terms of Use page URL
- Test the link to ensure it directs users to the correct page

### Acceptance Criteria

- The "Terms of Use" link in the footer directs users to the correct Terms of Use page
- The link is functional and works as expected

### Links

| [`FIGMA LINK`](LINK_HERE)
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=10-16358&t=5674AcOi1CIMUzZJ-0

### Images

![image](https://github.com/user-attachments/assets/1a2c3070-06ee-49db-b173-64a6eee02d1f)

**Comment by Muneerat** [comment]
I will work on this
