### ISSUE TITLE
[FEAT] Super Admin Nav Bar Component

### ISSUE THREAD

**Issue by SirhmVFX** [hngprojects/hng_boilerplate_nextjs#12]
### Description

Implement the Super Admin Nav Bar using ShadCN UI components. The Nav Bar should adhere strictly to the design specifications provided. Below are the detailed instructions and requirements.

**Requirements:**

1. **UI Components:**
   - Use ShadCN UI components for consistency.
   - Ensure all components match the design specifications provided.

2. **Design Specifications:**
   - Refer to the provided design for dimensions, colors, and layout.
   - Include all items as per the design: search bar, profile dropdown, notifications and help.

3. **Functionality:**
   - Include a dropdown for the user profile with options such as "Settings," "Profile," and "Logout."
   - Implement a help icon with a drop down showing options like "customer care", "FAQ"
   - Implement a notifications icon with a badge showing the number of unread notifications.

4. **Accessibility:**
   - Ensure all components are accessible and follow best practices

5. **Testing:**
   - Ensure the component renders correctly with all required elements.

**Acceptance Criteria:**

- [ ] The `SuperAdminNavBar` component is created and located in the `components` directory.
- [ ] All UI components are implemented using ShadCN UI.
- [ ] The Nav Bar matches the design specifications.
- [ ] The Nav Bar functions correctly 
- [ ] User profile dropdown is functional with appropriate options.
- [ ] Notifications icon with badge is implemented.
- [ ] All components are accessible 

**Attachments:**
![Screenshot 2024-07-17 at 13 07 35](https://github.com/user-attachments/assets/1d2583c7-b14f-4bb7-b535-72fa2ade0a0c)
[Link to Design file](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=2179-37958&m=dev)

- [ShadCN UI Documentation](https://ui.shadcn.com/)

**Comment by taiwonaf** [comment]
@SirhmVFX the dropdown menu requested for is missing in the design , if there is , please direct me to it
