### ISSUE TITLE
[BUG]: Fix Non-Functional Cancel Button in Password Settings 

### ISSUE THREAD

**Issue by akande1** [hngprojects/hng_boilerplate_nextjs#1207]
## Description:
In the password settings section for enhanced account security, after entering the current password, new password, and confirming the new password, two buttons are displayed: one for updating the password and one for canceling the process. The "Cancel" button is not working correctly—it does not clear the entered password information nor does it close the page, leaving the user unable to effectively cancel the operation.

## Expected Outcomes:
1. Cancel Button Functionality: The "Cancel" button should clear all input fields (current password, new password, confirm new password) when clicked.
2. Page Closure: If the cancel action is chosen, the page or modal for password update should close, returning the user to the previous screen or settings menu.
3. Smooth User Experience: Ensure that the cancel process does not save any inputted data and allows users to exit the process easily.

## Acceptance Criteria:
- Ensure the "Cancel" button clears all password input fields when clicked.
- Make sure the "Cancel" button closes the password update page or modal upon selection.
- Test the cancel functionality across different browsers and devices to confirm consistent behavior.
- Verify that no data is saved if the user chooses to cancel the password update.

link; https://kimiko-csharp.teams.hng.tech/dashboard/admin/settings/account
video; https://www.awesomescreenshot.com/video/30765970?key=cd9d148e21dbedc97bdabdfa239d21ec

**Comment by seshto13** [comment]
I will work on it
