### ISSUE TITLE
[Fix]: [FE ANCHOR] Logo and Address absent in footer 

### ISSUE THREAD

**Issue by Alphasome** [hngprojects/hng_boilerplate_nextjs#1208]
### Description

Description
The footer of the site currently lacks essential elements, including the logo and address.

User Story:
As a user, I want to see the logo, subject details, and address in the footer of the website.

### Acceptance Criteria

Requirement
1. Add the company logo to the footer
2. Display the company or office address in the footer.

Acceptance Criteria:
1. The footer includes the company logo and address.
2. The logo is correctly displayed and aligned.

Expected Outcome:

The footer is updated to include the company logo and address.

### Links

| [`[FIGMA LINK](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=10-23157&t=1TkEhfLMB1fQwC0P-0)`]
(LIVE_LINK - )

### Images

figma image - 
<img width="347" alt="image" src="https://github.com/user-attachments/assets/2fce7910-54e0-4062-b13a-d0301d053baf">

live link image - 
<img width="280" alt="image" src="https://github.com/user-attachments/assets/2c0957c7-76e2-45bb-9ea1-e90a4c620497">

**Comment by peter-abah** [comment]
working on this
