### ISSUE TITLE
[Enhancement]: Add Website Name to "All Rights Reserved" Text in Footer of the landing page

### ISSUE THREAD

**Issue by estialo1** [hngprojects/hng_boilerplate_nextjs#1209]
### Description

The footer currently displays "©2024 All Rights Reserved" without the website's name. To enhance brand visibility and ensure proper copyright attribution, the website's name "HNG Boilerplate" should be included in this text.

### Acceptance Criteria

- The website's name is correctly included in the "All Rights Reserved" text in the footer.
- The text is aligned with the rest of the footer content and does not disrupt the layout.

### Links

| [`FIGMA LINK`](LINK_HERE)
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=2084-18389

### Images

![image](https://github.com/user-attachments/assets/0613f16d-8a1c-4153-b18f-adbb197f57c6)

**Comment by Feng-09** [comment]
I will work on this

**Comment by estialo1** [comment]
Ok. Let me know when you are done with it
