### ISSUE TITLE
[FEAT] EMAIL TEMPLATES -> Subscription Cancellation Template

### ISSUE THREAD

**Issue by Saviourise** [hngprojects/hng_boilerplate_nextjs#121]
## Description

_Create a Subscription Cancellation email template according to the design using React Email_

## Acceptance Criteria

- The email template must be responsive
- The email template must be dynamic
- The email template must be done according to the design
- The email tempate must be created using React Email

### Requirements	

The following props should be available for the component

1. Title
2. Name
3. Image
4. Plan
5. Subscription ID
6. Subscribe again link
7. Cancellation data
8. Any other required props

### Tests

- [ ] Ensure template is responsive
- [ ] Ensure template can receive dynamic data according to what will be displayed
- [ ] Ensure template is displayed properly according to design and requirements

###  Tasks

- [ ] Create one dynamic email template using React Email
- [ ] Add props according to the type of text and data it will display (check the design to confirm what will be displayed)
- [ ] Template must be responsive on Bigger screens, tablet screens and mobile screens
- [ ] Create a unit test to ensure template works as expected

### TimeFrame

**The deadline for submission is Saturday 11:59PM**

# LINKS

[`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=114-14277&m=dev).
[`REACT EMAIL DOCS`](https://react.email/docs/components/html).

# IMAGES
![Subscription Cancellation (3)](https://github.com/user-attachments/assets/d29e1b9f-56de-4237-b57e-3d9c3ce48325)
![Subscription Cancellation (2)](https://github.com/user-attachments/assets/fb140641-0a48-47bb-be44-239a2a50b52d)
![Subscription Cancellation (1)](https://github.com/user-attachments/assets/8f379b50-acca-4236-9992-974e82d8976f)
![Subscription Cancellation](https://github.com/user-attachments/assets/daf8a57a-5d0e-42e4-988e-b6f73cbf7127)

**Comment by danthecm** [comment]
@Saviourise  use HTML and CSS for all Email Templates

**Comment by Saviourise** [comment]
@danthecm and @chumex412 please review
