### ISSUE TITLE
[Bug]: [FE Anchor] Multiple Time-Zone Entries Selected Simultaneously in Language & Region Settings page

### ISSUE THREAD

**Issue by Akynz-x** [hngprojects/hng_boilerplate_nextjs#1211]
### Description

On the **Language & Region settings** page of the **Admin Dashboard**, when the user attempts to select a single time zone from the dropdown, multiple entries are selected at the same time. This behavior makes it impossible for users to choose the correct time zone, leading to potential errors in saving changes.
### Requirements:
- Ensure that only one time zone can be selected at any given time.
- Ensure proper selection and deselection behavior in the dropdown.
### Expected Outcome:
- Only the selected time zone should be highlighted, with no other entries selected.

### Acceptance Criteria

- A user can select only one time zone from the dropdown.
- Selecting a new time zone automatically deselects the previous selection.
- No multiple selections should occur when a single time zone is clicked.

### Links

| [`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=10-16364&t=vIy051gXQHK49sRP-4)

| [`ADMIN SETTINGS PAGE`](https://anchor-python.teams.hng.tech/dashboard/admin/settings/language-and-region)

### Images

![Screenshot (26)](https://github.com/user-attachments/assets/2d1bd1e0-0650-49bd-8464-f57bd3ec54b0)

**Comment by peter-abah** [comment]
working on this
