### ISSUE TITLE
[FEATURE]: Create Toggle Input Box

### ISSUE THREAD

**Issue by judeb21** [hngprojects/hng_boilerplate_nextjs#122]
## Description
Develop a toggle input component. This component must maintain all states according to design. This switch component should be visually appealing as well as functional. It will be used across all pages.

### Requirements

- [ ] Ensure UI consistency
- [ ] Ensure Component can receive prop values
- [ ] Ensure component can emit prop values to where needed
- [ ] Develop component according to the design

### Acceptance Criteria

- Toggle Input Component should be implemented according to the design
- Write test to assert functionality
- The component must be functional, it will be used across all pages

### Links

[Figma link](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=2225-8100&m=dev)

**Comment by danthecm** [comment]
@judeb21  Duplicate: https://github.com/hngprojects/hng_boilerplate_nextjs/issues/108
