### ISSUE TITLE
[Fix]: Adjust Right Margin Under Notifications Page

### ISSUE THREAD

**Issue by delight-xxx** [hngprojects/hng_boilerplate_nextjs#1222]
### Description

Current state: The right margin on the Notification Settings page is too small, causing the "Save Changes" button and the toggle switches to appear too close to the edge of the screen. 
Note the difference in margins on the design and the live links.

### Requirements

Increase the right margin or padding on the Notification Settings page to provide sufficient space between the UI elements and the edge of the screen. 

### Expected Outcome

The page should have a sufficient right margin to ensure that all elements(Toggle switches and "Save changes" button are comfortably spaced from the edge of the screen

### Links

| [`LIVE LINK`](https://kimiko-csharp.teams.hng.tech/dashboard/admin/settings/notification)

### Images

![image](URL_HERE)
Design:
<img width="1049" alt="Screenshot 2024-08-22 at 11 42 31 PM" src="https://github.com/user-attachments/assets/ba96a589-10a9-4741-82b0-7a9dc6f4d35f">

Live Link: 

<img width="1503" alt="Screenshot 2024-08-22 at 11 46 56 PM" src="https://github.com/user-attachments/assets/ad4db765-41aa-447b-bfd6-b9f456440a31">
![Uploading Screenshot 2024-08-22 at 11.46.56 PM.png…]()

**Comment by seshto13** [comment]
I will work on it
