### ISSUE TITLE
[Feature]: [FE ANCHOR] Integrate Blog Data Fetching from Backend 

### ISSUE THREAD

**Issue by Mary-chisom-pm** [hngprojects/hng_boilerplate_nextjs#1233]
### Description

Implement functionality to fetch blog data from the backend and display it on the front end. This will allow the blog section to dynamically display the latest blog posts and related content by retrieving data from the backend API.

### Acceptance Criteria

Data Retrieval:

When the user accesses the blog section, the latest blog posts should be fetched from the backend and displayed dynamically.

If there are multiple blog posts, they should be displayed with pagination.

### Links

[LIVE LINK](https://anchor-python.teams.hng.tech/blog)

##VIDEO DESCRIPTION
(https://github.com/user-attachments/assets/8bd1ac8d-c222-4960-b8f9-52cb87cd86e1)

**Comment by Feng-09** [comment]
Working on this
