### ISSUE TITLE
[Enhancement]: [FE ANCHOR] Fix Responsiveness for Waitlist Page

### ISSUE THREAD

**Issue by Boyeadelo** [hngprojects/hng_boilerplate_nextjs#1238]
### Description

The waitlist page is currently not responsive for all screens. It should adjust seamlessly across different screen sizes, ensuring optimal user experience on all devices.

### Acceptance Criteria

1. The waitlist page adapts to different screen sizes (mobile, tablet, desktop) without layout issues.

2. No horizontal scrolling is required on mobile devices except for the “We have got you covered” section where users would be required to scroll horizontally on the navigation bar in that section.

### Links

| [`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=21406-25724&t=5LIpFRAhzllD5nyS-4)

| [`LIVE LINK`](https://anchor-java.teams.hng.tech/waitlist)

### Images

![image](https://github.com/user-attachments/assets/aeae2743-8896-4769-8358-f97375b080a7)
![image](https://github.com/user-attachments/assets/2761952b-536e-472e-a523-76723d492197)
![image](https://github.com/user-attachments/assets/c0bbcb8b-4a49-423f-9a43-5fb964e1a2cb)

**Comment by seshto13** [comment]
I will work on this
