### ISSUE TITLE
[Feature]: Create About Us Page

### ISSUE THREAD

**Issue by judeb21** [hngprojects/hng_boilerplate_nextjs#125]
### Description

Create and Implement the about us page. This page must be fully responsive and implemented according to the design

### Acceptance Criteria

- Page must be fully responsive on mobile, tablets and desktops
- Page must fully implement what was designed
- Page must use reusable components already existing

### Test

- Test page is fully responsive
- Ensure page uses existing components
- Ensure buttons and links works appropriately

### Links

https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=4-21184&m=dev

### Image 
<img width="665" alt="Screenshot 2024-07-18 at 08 17 46" src="https://github.com/user-attachments/assets/69f6cba8-52b1-4885-b733-678751bd71ac">

**Comment by danthecm** [comment]
@judeb21 include images and test requirements

**Comment by judeb21** [comment]
@danthecm Done

**Comment by kingbary** [comment]
I am working on this guys

**Comment by iamyelex** [comment]
is anyone working on this? assign it to me @judeb21

**Comment by MUdugbesi** [comment]
This is a duplicate @iamyelex - its the same issue with #45 . Issue should have been closed
