### ISSUE TITLE
[Feature]: Create Help Center Page

### ISSUE THREAD

**Issue by judeb21** [hngprojects/hng_boilerplate_nextjs#126]
### Description

Create and Implement the Help Center Page. This page must be fully responsive and implemented according to the design

### Acceptance Criteria

- Page must be fully responsive on mobile, tablets and desktops

- Page must fully implement what was designed

- Page must use reusable components already existing

### Test

- Test page is fully responsive
- Ensure page uses existing components
- Ensure buttons and links works appropriately

### Links

https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=4-21184&m=dev

### Image
<img width="671" alt="Screenshot 2024-07-18 at 08 21 08" src="https://github.com/user-attachments/assets/5858e204-febc-46fa-bd4c-bf64b147e3b5">

**Comment by danthecm** [comment]
@judeb21 include images and test

**Comment by judeb21** [comment]
@danthecm Done
