### ISSUE TITLE
[Enhancement]: [FE Anchor] Add Mismatch Error for New Password and Confirm New Password Fields on Password Settings page

### ISSUE THREAD

**Issue by Akynz-x** [hngprojects/hng_boilerplate_nextjs#1268]
### Description

The "New Password" and "Confirm New Password" fields currently do not trigger a mismatch error if the entries in these fields do not match. This can lead to user frustration and failed password updates.

### Purpose:
To ensure users are alerted to discrepancies between their New Password and Confirm New Password entries in real-time, preventing potential errors during password updates.

### Acceptance Criteria

- [ ] An error message appears when the "New Password" and "Confirm New Password" fields do not match.
- [ ] The error message is clear and easy to understand.
- [ ] The error message disappears when the fields match.
- [ ] The validation works across all supported browsers and device types.
### Requirements:
- Implement real-time validation that triggers an error message when the entries in the "New Password" and "Confirm New Password" fields do not match.
- The error message should be clear, indicating that the passwords do not match and need to be corrected.
- The error message should disappear when the two fields match.
### Expected Outcome:
Users receive an immediate error message if the "New Password" and "Confirm New Password" fields do not match, and the message disappears once the fields match.

### Links

| [`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=10-16364&t=vIy051gXQHK49sRP-4)
| [`PASSWORD SETTINGS PAGE`](https://anchor-java.teams.hng.tech/dashboard/admin/settings/account)

### Images

![Screenshot (35)](https://github.com/user-attachments/assets/87bc3e6e-aba1-40e4-b0fc-b5b7b05b49d2)

**Comment by abdulmalikyusuf** [comment]
I am on this
