### ISSUE TITLE
[Feature]: Email Templates > SuperAdmin Email Management Dashboard > Dashboard Pagination Component

### ISSUE THREAD

**Issue by elitenoire** [hngprojects/hng_boilerplate_nextjs#127]
### Description

Create a Pagination Component used in the Super Admin Email Management Dashboard

### Acceptance Criteria

- [x] Reusable Pagination Component
- [x] Pagination is built on top of shadcn-ui pagination component
- [x] Component displays page numbers and total pages
- [x] Component has left and right navigation buttons
- [x] Component has number navigation buttons
- [x] Component has a fluid width
- [x] Component implements different style for current / active page
- [x] Component adheres to the brand design and colors
- [x] Component is responsive across devices

![pagination](https://github.com/user-attachments/assets/bd6d7483-1492-4326-b476-bc7c42ed5939)

### Links

Figma: https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=2319-9865&m=dev

**Comment by sim-codes** [comment]
Hi, can how can I get this issue approved so I can have an issue to work on?
