### ISSUE TITLE
[Fix]: Remove Extra Text from "Login" Link on Sign-Up Page

### ISSUE THREAD

**Issue by estialo1** [hngprojects/hng_boilerplate_nextjs#1284]
### Description

There is extra text present around the "Login" link on the Sign-Up page, which may cause confusion for users. The text "Login" appears twice, making it redundant. 

### Acceptance Criteria

Only one "Login" link is displayed under the "Create Account" button on the Sign-Up page.

### Links

| [`FIGMA LINK`](LINK_HERE)

### Images

![image](https://github.com/user-attachments/assets/9f4bb336-b96b-4463-8b5d-691f785b21e2)

**Comment by seshto13** [comment]
I will work on it

**Comment by estialo1** [comment]
ok. drop your PR when you are done.

**Comment by seshto13** [comment]
My PR is https://github.com/hngprojects/hng_boilerplate_nextjs/pull/1514.

**Comment by estialo1** [comment]
ok
