### ISSUE TITLE
[Feature]: Develop Not Found and Empty State Components for Job Listings Search and Filter

### ISSUE THREAD

**Issue by SilverBeing** [hngprojects/hng_boilerplate_nextjs#129]
### Description

Develop components to handle "Not Found" and "Empty State" scenarios for the job listings search and filter functionalities. These components should display appropriate messages and match the design specifications.

### Acceptance Criteria

- [ ] Develop a "Not Found" component to display when no job listings match the search or filter criteria.
- [ ] Develop an "Empty State" component to display when there are no job listings available.
- [ ] Ensure the components match the provided design specifications and are responsive.
- [ ] Collaborate with the intern working on the job listings page, ensuring they display under the appropriate conditions
- [ ] Write unit tests to verify the display of "Not Found" and "Empty State" components under the correct conditions.

### Links

https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=417-23348&m=dev
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=417-23429&m=dev
![Uploading Screenshot 2024-07-17 175448.png…]()

**Comment by CollinXon** [comment]
Hello, I will like to work on this feature. Also I'm not seeing the exact figma design for this component on the link
