### ISSUE TITLE
[Feature]: MEMBERS PAGE NOT ALIGNED PROPERLY FOR MOBILE VERSION

### ISSUE THREAD

**Issue by Benjam1n7** [hngprojects/hng_boilerplate_nextjs#1295]
### Description

The members page and password settings page shows a desktop view on mobile phone

### Acceptance Criteria

Properly aligned and MEMBERS page for mobile version

### Links

| [`FIGMA LINK`](LINK_HERE)

**Comment by Benjam1n7** [comment]
![WhatsApp Image 2024-08-23 at 7 21 27 PM](https://github.com/user-attachments/assets/44f8424a-41f0-4374-bdc3-5c24ef5fe944)

**Comment by Chioma227** [comment]
This is a duplicate issue.
It already exists.

**Comment by Benjam1n7** [comment]
OKAY
