### ISSUE TITLE
[Feature]: PRIVACY POLICY LINKJ NOT RESPONSIVE ON LOGIN PAGE 

### ISSUE THREAD

**Issue by Benjam1n7** [hngprojects/hng_boilerplate_nextjs#1303]
### Description

The Privacy policy link not responsive on the login page

### Acceptance Criteria

The link directs user to a privacy policy page after first click

### Links

| [`FIGMA LINK`](LINK_HERE)

### Images

![image](URL_HERE)

Uploading WhatsApp Video 2024-08-23 at 8.23.46 PM.mp4…

**Comment by Chioma227** [comment]
This is a duplicate issue.
It has already been worked on.

**Comment by Benjam1n7** [comment]
OKAY
