### ISSUE TITLE
[Feature]: Create Privacy Page

### ISSUE THREAD

**Issue by judeb21** [hngprojects/hng_boilerplate_nextjs#131]
### Description

Create and Implement the Privacy Page. This page must be fully responsive and implemented according to the design

### Acceptance Criteria

- Page must be fully responsive on mobile, tablets and desktops
- Page must fully implement what was designed
- Page must use reusable components already existing

### Links

https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=4-23901&m=dev

### Image
<img width="623" alt="Screenshot 2024-07-19 at 14 07 29" src="https://github.com/user-attachments/assets/d9089dfb-ae94-49ab-88d7-698deab0709c">
<img width="311" alt="Screenshot 2024-07-19 at 14 08 48" src="https://github.com/user-attachments/assets/ebe33ec3-a647-418f-a2d9-72322a59b048">

**Comment by JulianaSau** [comment]
@judeb21 Also include an image of this page on the task description

@JulianaSau Done

**Comment by chumex412** [comment]
Please get and integrate the already implemented Navbar and footer. Do not implement yours.

@wunmicrown Use the navbar and footer component already implemented, do not implement yours

**Comment by Emmanuel-Xs** [comment]
Please this is a duplicate of issue #47.

I am done with my implementation just waiting for the breadcrumbs components #59 and sub page hero section #56

**Comment by deverins** [comment]
@Emmanuel-Xs but is mentor that assigned this issue to me

**Comment by deverins** [comment]
@Emmanuel-Xs Am already working on it and i can't leave this ticket

**Comment by Emmanuel-Xs** [comment]
look at when i assigned my self the issue, yesterday, should i leave it for you when you just picked it 5hrs ago, come on be considerate na
