### ISSUE TITLE
[Feature]: EMAIL TEMPLATES -> Subscription Confirmation Template

### ISSUE THREAD

**Issue by Saviourise** [hngprojects/hng_boilerplate_nextjs#132]
### Description

_Create a Subscription Confirmation email template according to the design using React Email_

### Acceptance Criteria

- The email template must be responsive
- The email template must be dynamic
- The email template must be done according to the design
- The email tempate must be created using React Email

### Requirements	

The following props should be available for the component

1. Title
2. Name
3. Image
4. Email
5. Subscription Plan
6. Cost
7. Duration
8. Subscription Start date
9. Estimated Expiry date
10. Unsubscribe Link
11. Any other required props

### Tests

- [ ] Ensure template is responsive
- [ ] Ensure template can receive dynamic data according to what will be displayed
- [ ] Ensure template is displayed properly according to design and requirements

###  Tasks

- [ ] Create one dynamic email template using React Email
- [ ] Add props according to the type of text and data it will display (check the design to confirm what will be displayed)
- [ ] Template must be responsive on Bigger screens, tablet screens and mobile screens
- [ ] Create a unit test to ensure template works as expected

### TimeFrame

**The deadline for submission is Saturday 11:59PM**

### Links

[`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=2156-26514&m=dev).
[`REACT EMAIL DOCS`](https://react.email/docs/components/html).

# IMAGES
![Subscription Confirmation (3)](https://github.com/user-attachments/assets/21ff3342-011f-456e-a3fe-b0c718f892b6)
![Subscription Confirmation (2)](https://github.com/user-attachments/assets/66f46959-3748-4f28-bd31-d0636719a4d9)
![Subscription Confirmation (1)](https://github.com/user-attachments/assets/2007ce66-f29e-4052-b10c-d06239b5ca8c)
![Subscription Confirmation](https://github.com/user-attachments/assets/77ec8ce5-8f1d-40d1-8b1a-08030e7b96d3)

**Comment by Saviourise** [comment]
@chumex412 please review

**Comment by iamyelex** [comment]
is this task still available? i will take it.

**Comment by iamyelex** [comment]
I have assign this to myself.
