### ISSUE TITLE
[FEAT] Super Admin User Details Page

### ISSUE THREAD

**Issue by SirhmVFX** [hngprojects/hng_boilerplate_nextjs#136]
### Description:
---

Using the already existing component, Implement the Super Admin User Details Page, ensuring consistency with ShadCN UI components. Below are the detailed instructions and requirements.

**Requirements:**

1. **Page Components:**
   - Use existing components and match the design specifications provided in the design.

2. **Design Specifications:**
   - Refer to the provided design for dimensions, colors, and layout.

3. **Accessibility:**
   - Ensure the components is accessible and follow best practices

4. **Testing:**
   - Ensure the pages renders correctly with all required elements.

**Acceptance Criteria:**

- [ ] Pages Should be pixel perfect as implemented using ShadCN UI.
- [ ] Implement interactions with the pages 

**Attachments:**
![Screenshot 2024-07-17 at 18 06 20](https://github.com/user-attachments/assets/14a59bcd-9eaa-40ee-8788-0cf3dbbcb431)

[Link to the design file](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=413-20441&m=dev)

- [ShadCN UI Documentation](https://ui.shadcn.com/)

**Comment by chumex412** [comment]
This ticket is generic and doesn't give enough context

**Comment by SirhmVFX** [comment]
@chumex412 edited it already

**Comment by chumex412** [comment]
What component on the user details page pops up and closes smoothly, boss

It seems you just copied and pasted, hence, why I said it's generic.

**Comment by SirhmVFX** [comment]
Ohhh... so sorry boss, I've fixed it now @chumex412
