### ISSUE TITLE
[Feature]: Create Waitlist Page

### ISSUE THREAD

**Issue by judeb21** [hngprojects/hng_boilerplate_nextjs#137]
### Description

Create and Implement the Waitlist Page. This page must be fully responsive and implemented according to the design

### Acceptance Criteria

- Page must be fully responsive on mobile, tablets and desktops

- Page must fully implement what was designed

- Page must use reusable components already existing

### Links

https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=518-7647&m=dev

**Comment by SilverBeing** [comment]
This task is dependent on #138 #137 #111 #99
