### ISSUE TITLE
[Feature]: Develop Form on the Waitlist Page to Add Users to the Waitlist

### ISSUE THREAD

**Issue by SilverBeing** [hngprojects/hng_boilerplate_nextjs#138]
### Description

Develop a form component for the waitlist page that collects user information (such as name, email address, and optionally phone number) and integrates with backend API endpoints to add users to the waitlist. Ensure the form matches the design specifications, handles form validation, and provides a smooth user experience.

### Acceptance Criteria

- [x] Develop a form with fields for user's name, email address.
- [x] Implement form validation to ensure required fields are filled and valid email format is entered.
- [ ] Integrate the form with backend API endpoints to add users to the waitlist.
- [x] Display success or error messages based on API response.
- [x] Ensure the form matches the provided design specifications and is responsive.
- [x] Write unit tests to verify form validation, API integration, and responsiveness

**Deadline Friday 10am**
### Links

https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=518-7790&m=dev
![image](https://github.com/user-attachments/assets/12263b0f-72a7-45ea-a6e1-73492a77e4c4)

**Comment by G4EVA-dev** [comment]
Please for this issue, to be sure I'm building just the form right?
I'm a front-end developer
