### ISSUE TITLE
[Feature]: EMAIL TEMPLATES -> New Feature Announcement Template

### ISSUE THREAD

**Issue by Saviourise** [hngprojects/hng_boilerplate_nextjs#139]
## Description

_Create a New Feature Announcement email template according to the design using React Email_

### Acceptance Criteria

- The email template must be responsive
- The email template must be dynamic
- The email template must be done according to the design
- The email tempate must be created using React Email

### Requirements	

The following props should be available for the component

1. Title
2. Name
3. Image
4. Feature name
5. Description of feature
6. Benefits of feature
7. Any other required props

### Tests

- [ ] Ensure template is responsive
- [ ] Ensure template can receive dynamic data according to what will be displayed
- [ ] Ensure template is displayed properly according to design and requirements

###  Tasks

- [ ] Create one dynamic email template using React Email
- [ ] Add props according to the type of text and data it will display (check the design to confirm what will be displayed)
- [ ] Template must be responsive on Bigger screens, tablet screens and mobile screens
- [ ] Create a unit test to ensure template works as expected

### TimeFrame

**The deadline for submission is Saturday 11:59PM**

### Links

[`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=67-37765&m=dev).
[`REACT EMAIL DOCS`](https://react.email/docs/components/html).

# IMAGES
![New Feature Announcement (3)](https://github.com/user-attachments/assets/f1808bb2-310e-4783-89d1-2d73456cee52)
![New Feature Announcement (2)](https://github.com/user-attachments/assets/e5652543-2f8a-475f-bc69-8ed48836ac50)
![New Feature Announcement (1)](https://github.com/user-attachments/assets/eff0ba50-ad92-49a5-a275-c733964a526c)
![New Feature Announcement](https://github.com/user-attachments/assets/544a17da-2f28-4902-aa2a-2bade1be8480)

**Comment by chumex412** [comment]
Please indicate that it should be developed with the React email package

**Comment by Saviourise** [comment]
@chumex412 I have done that, please review

**Comment by ux-finesse** [comment]
There are 4 different screens here, am I to pick one? Or? @chumex412

**Comment by chumex412** [comment]
Four different screens? how? Where?
Please there are only two main categories.

One with images for desktop and mobile

The second without images for desktop and mobile.

**Comment by ux-finesse** [comment]
Yeah 2 screens I meant, 
so am I to develop both of them (with images and without images)? @chumex412

**Comment by Saviourise** [comment]
@ux-finesse you are to develop only one screen. That screen will be responsive and will take in image as props. If the image is available, it will show the image, else it will not show the image. Please thoroughly go through the instructions

**Comment by ux-finesse** [comment]
Okay cool, all done
