### ISSUE TITLE
[Feature]: EMAIL TEMPLATES -> Newsletter Template

### ISSUE THREAD

**Issue by Saviourise** [hngprojects/hng_boilerplate_nextjs#141]
### Description

_Create a Newsletter email template according to the design using React Email_

### Acceptance Criteria

- The email template must be responsive
- The email template must be dynamic
- The email template must be done according to the design
- The email tempate must be created using React Email

### Requirements	

The following props should be available for the component

1. Title
2. Name
3. Image
4. Newsletter Content
5. Learn more Link
6. Any other required props

### Tests

- [ ] Ensure template is responsive
- [ ] Ensure template can receive dynamic data according to what will be displayed
- [ ] Ensure template is displayed properly according to design and requirements

###  Tasks

- [ ] Create one dynamic email template using React Email
- [ ] Add props according to the type of text and data it will display (check the design to confirm what will be displayed)
- [ ] Template must be responsive on Bigger screens, tablet screens and mobile screens
- [ ] Create a unit test to ensure template works as expected

### TimeFrame

**The deadline for submission is Saturday 11:59PM**

### Links

[`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=67-38539&m=dev).
[`REACT EMAIL DOCS`](https://react.email/docs/components/html).

# IMAGES
<img width="430" alt="Newsletter Mobile (1)" src="https://github.com/user-attachments/assets/d583a925-d775-4d94-af35-0d969b984b7f">
<img width="430" alt="Newsletter (1)" src="https://github.com/user-attachments/assets/1c4c3694-071d-46a2-8413-f7e0e28d15cb">
<img width="430" alt="Newsletter Mobile" src="https://github.com/user-attachments/assets/3451b1e9-08fa-42e3-890d-8c0d53e2150e">
<img width="430" alt="Newsletter" src="https://github.com/user-attachments/assets/71f19e9c-4a9b-4d85-a9e3-e9ea5a8f5a3c">

**Comment by chumex412** [comment]
Please indicate that it should be developed with the React email package

**Comment by Saviourise** [comment]
@chumex412 I have done that, please review

**Comment by MazinoCodes** [comment]
Can I get some clarification on where the newsletter content and image props go

**Comment by Saviourise** [comment]
@MazinoCodes go through the design. you will see where the props go

**Comment by MazinoCodes** [comment]
Should I also add the header and footer or is that another issue?
