### ISSUE TITLE
[Feature]: PRONOUNS SECTION WRONGLY DISPLAYING SELECT LANGUAGE

### ISSUE THREAD

**Issue by Benjam1n7** [hngprojects/hng_boilerplate_nextjs#1435]
### Description

The pronouns section is incorrectly displaying 'SELECT LANGUAGE' whuch s wrong. 

### Acceptance Criteria

It should display 'select' and not language 

### Links

| [`FIGMA LINK`](LINK_HERE)

### Images

![image](URL_HERE)
![WhatsApp Image 2024-08-24 at 11 21 07 AM](https://github.com/user-attachments/assets/f5e189ca-884a-4e03-893d-18523d129dc4)

**Comment by Muneerat** [comment]
this is a duplicate @Benjam1n7

**Comment by Benjam1n7** [comment]
OKAY
