### ISSUE TITLE
[Feature]: EMAIL TEMPLATES -> Payment Receipt Template

### ISSUE THREAD

**Issue by Saviourise** [hngprojects/hng_boilerplate_nextjs#144]
### Description

_Create a Payment Receipt email template according to the design using React Email_

### Acceptance Criteria

- The email template must be responsive
- The email template must be dynamic
- The email template must be done according to the design
- The email tempate must be created using React Email

### Requirements	

The following props should be available for the component

1. Title
2. Image
3. Order Summary Details
4. Payment Details
5. Any other required props

### Tests

- [ ] Ensure template is responsive
- [ ] Ensure template can receive dynamic data according to what will be displayed
- [ ] Ensure template is displayed properly according to design and requirements

###  Tasks

- [ ] Create one dynamic email template using React Email
- [ ] Add props according to the type of text and data it will display (check the design to confirm what will be displayed)
- [ ] Template must be responsive on Bigger screens, tablet screens and mobile screens
- [ ] Create a unit test to ensure template works as expected

### TimeFrame

**The deadline for submission is Saturday 11:59PM**

### Links

[`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=1809-11333&m=dev).
[`REACT EMAIL DOCS`](https://react.email/docs/components/html).

# IMAGES
![Payment receipt mobile (1)](https://github.com/user-attachments/assets/57121702-a83a-4e4c-af34-1ebc938219ff)
![Payment receipt (1)](https://github.com/user-attachments/assets/567e4032-c2d9-4c1b-b0a6-851693d9d444)
![Payment receipt mobile](https://github.com/user-attachments/assets/e47d08a6-1358-4cf9-9c7d-751aacfccce1)
![Payment receipt](https://github.com/user-attachments/assets/c01a7ec9-aff0-4682-afb5-6d914b41a45a)

**Comment by chumex412** [comment]
Please indicate that it should be developed with the React email package

**Comment by Saviourise** [comment]
@chumex412 I have done that, please review

**Comment by ifeanyiHM** [comment]
there's an issue with accessing react email docs, thought it was my connection initially and i can't work on task if i can't access the docs
