### ISSUE TITLE
[Feature]: Implement Search Functionality for FAQs with Reusable FAQ Card Component

### ISSUE THREAD

**Issue by SilverBeing** [hngprojects/hng_boilerplate_nextjs#145]
### Description

Implement search functionality for FAQs that allows users to search by keywords and retrieve relevant FAQs. Develop and integrate a reusable FAQ card component to display each FAQ item retrieved from the backend API or a static data. Ensure the search functionality is efficient and the FAQ cards match the provided design specifications.

### Acceptance Criteria

- [ ] Develop a search input field for entering keywords to search FAQs.
- [ ] Implement the logic to fetch FAQs based on search keywords.
- [ ] Display search results using the reusable FAQ card component.
- [ ] Ensure the FAQ cards display relevant information such as question, answer, and any tags.
- [ ] Ensure the search functionality and FAQ display match the provided design specifications and are responsive.
- [ ] Write unit tests to verify search functionality, API integration, and responsiveness.

Deadline- Friday 10pm

### Links

https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=432-7523&m=dev
![image](https://github.com/user-attachments/assets/4512dc04-1d1c-4fc8-bce1-1c41b120235e)

**Comment by kingstech001** [comment]
Is anyone working on this

**Comment by MUFTIATBAKARE** [comment]
yes

**Comment by MUFTIATBAKARE** [comment]
This is my ticket, please
