### ISSUE TITLE
[Feature]: EMAIL TEMPLATES -> Invoice Email Template

### ISSUE THREAD

**Issue by Saviourise** [hngprojects/hng_boilerplate_nextjs#153]
### Description

_Create a Invoice email template according to the design using React Email_

### Acceptance Criteria

- The email template must be responsive
- The email template must be dynamic
- The email template must be done according to the design
- The email tempate must be created using React Email

### Requirements	

The following props should be available for the component

1. Title
2. Name
3. Image
4. Invoice Details
5. Payment Details
6. Order summary details
7. Pay now liink
8. Any other required props

### Tests

- [ ] Ensure template is responsive
- [ ] Ensure template can receive dynamic data according to what will be displayed
- [ ] Ensure template is displayed properly according to design and requirements

###  Tasks

- [ ] Create one dynamic email template using React Email
- [ ] Add props according to the type of text and data it will display (check the design to confirm what will be displayed)
- [ ] Template must be responsive on Bigger screens, tablet screens and mobile screens
- [ ] Create a unit test to ensure template works as expected

### TimeFrame

**The deadline for submission is Saturday 11:59PM**

### Links

[`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=67-30078&m=dev).
[`REACT EMAIL DOCS`](https://react.email/docs/components/html).

# IMAGES
![Invoice Email (3)](https://github.com/user-attachments/assets/d493bd6c-40ce-4740-8880-057ee7331d44)
![Invoice Email (2)](https://github.com/user-attachments/assets/485748f1-6d27-4c29-945d-32d5fb9f12f3)
![Invoice Email (1)](https://github.com/user-attachments/assets/f86b6a3f-7c5b-4036-9873-e5e5efc05133)
![Invoice Email](https://github.com/user-attachments/assets/76faac05-5ca8-47b6-a624-5c926209827c)

**Comment by chumex412** [comment]
Please indicate that it should be developed with the React email package

**Comment by Saviourise** [comment]
@chumex412 I have done that, please review
