### ISSUE TITLE
[Feature]: AUTHENTICATION -> EMAIL TEMPLATE -> Account Deactivation by User Template

### ISSUE THREAD

**Issue by Saviourise** [hngprojects/hng_boilerplate_nextjs#156]
### Description

_Create a Account Deactivation by User email template according to the design using React Email_

### Acceptance Criteria

- The email template must be responsive
- The email template must be dynamic
- The email template must be done according to the design
- The email template must be created with React Email

### Requirements	

The following props should be available for the component

1. Title
2. Name
3. Image
4. Deactivation details
5. Any other required props

### Tests

- [ ] Ensure template is responsive
- [ ] Ensure template can receive dynamic data according to what will be displayed
- [ ] Ensure template is displayed properly according to design and requirements

###  Tasks

- [ ] Create one dynamic email template using React Email
- [ ] Add props according to the type of text and data it will display (check the design to confirm what will be displayed)
- [ ] Template must be responsive on Bigger screens, tablet screens and mobile screens
- [ ] Create a unit test to ensure template works as expected

### TimeFrame

**The deadline for submission is Saturday 11:59PM**

### Links

[`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=1995-24485&m=dev).
[`REACT EMAIL DOCS`](https://react.email/docs/components/html)

# IMAGES
![Account Deactivation by User (7)](https://github.com/user-attachments/assets/b818e23e-95a6-4091-b8ba-0c4e292c617a)
![Account Deactivation by User (6)](https://github.com/user-attachments/assets/3cb8516b-4746-44f7-ac4a-c8319e012e19)
![Account Deactivation by User (5)](https://github.com/user-attachments/assets/e0d1ee23-0f39-4dd0-be13-ac761a696a6c)
![Account Deactivation by User (4)](https://github.com/user-attachments/assets/06d97976-7f24-4a45-8a9a-71b1c0cb9220)

**Comment by chumex412** [comment]
Please indicate that it should be developed with the React email package

**Comment by Saviourise** [comment]
@chumex412 I have made the changes, please review
