### ISSUE TITLE
[Feature]: AUTHENTICATION -> EMAIL TEMPLATE -> Account Deactivation by Inactivity Template

### ISSUE THREAD

**Issue by Saviourise** [hngprojects/hng_boilerplate_nextjs#157]
### Description

_Create a Account Deactivation by Inactivity email template according to the design using React Email_

### Acceptance Criteria

- The email template must be responsive
- The email template must be dynamic
- The email template must be done according to the design
- The email template must be created using React Email

### Requirements	

The following props should be available for the component

1. Title
2. Name
3. Image
4. Deactivation details
5. Any other required props

### Tests

- [ ] Ensure template is responsive
- [ ] Ensure template can receive dynamic data according to what will be displayed
- [ ] Ensure template is displayed properly according to design and requirements

###  Tasks

- [ ] Create one dynamic email template using React Email
- [ ] Add props according to the type of text and data it will display (check the design to confirm what will be displayed)
- [ ] Template must be responsive on Bigger screens, tablet screens and mobile screens
- [ ] Create a unit test to ensure template works as expected

### TimeFrame

**The deadline for submission is Saturday 11:59PM**

### Links

[`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=1995-24427&m=dev).
[`REACT EMAIL DOCS`](https://react.email/docs/components/html).

# IMAGES
![Account Deactivation by Inactivity (3)](https://github.com/user-attachments/assets/78ef1489-2c06-4f49-93bd-9bbcb81d09cd)
![Account Deactivation by Inactivity (2)](https://github.com/user-attachments/assets/f208ae53-156a-425b-b412-95a513a5436c)
![Account Deactivation by Inactivity (1)](https://github.com/user-attachments/assets/1bb247f5-c247-4a8f-a908-232cb6624252)
![Account Deactivation by Inactivity](https://github.com/user-attachments/assets/2d6fb0ba-d82c-4de4-b8b6-74cb387e741f)

**Comment by chumex412** [comment]
Please indicate that it should be developed with the React email package

**Comment by Saviourise** [comment]
@chumex412 i have done that, please review
