### ISSUE TITLE
[Feature]: AUTHENTICATION -> EMAIL TEMPLATE -> Incoming Account Deactivation Template

### ISSUE THREAD

**Issue by Saviourise** [hngprojects/hng_boilerplate_nextjs#159]
### Description

_Create a Incoming Account Deactivation email template according to the design using React Email_

### Acceptance Criteria

- The email template must be responsive
- The email template must be dynamic
- The email template must be done according to the design
- The email template must be created using React Email

### Requirements	

The following props should be available for the component

1. Title
2. Name
3. Image
4. Deactivation details
5. Access my account link
6. Any other required props

### Tests

- [ ] Ensure template is responsive
- [ ] Ensure template can receive dynamic data according to what will be displayed
- [ ] Ensure template is displayed properly according to design and requirements

###  Tasks

- [ ] Create one dynamic email template using React Email
- [ ] Add props according to the type of text and data it will display (check the design to confirm what will be displayed)
- [ ] Template must be responsive on Bigger screens, tablet screens and mobile screens
- [ ] Create a unit test to ensure template works as expected

### TimeFrame

**The deadline for submission is Saturday 11:59PM**

### Links

[`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=1995-24397&m=dev).
[`REACT EMAIL DOCS`](https://react.email/docs/components/html).

# IMAGES
![Incoming Account Deactivation (3)](https://github.com/user-attachments/assets/8e3bd4b5-522c-4aa4-af08-0510af7f765a)
![Incoming Account Deactivation (2)](https://github.com/user-attachments/assets/8d114bfe-7238-4357-99b0-b5e354fc31bd)
![Incoming Account Deactivation (1)](https://github.com/user-attachments/assets/3d3033a0-bbc7-4d9d-bcb4-029aa77888b0)
![Incoming Account Deactivation](https://github.com/user-attachments/assets/10820729-2c4d-46e9-b309-51908aeb3591)

**Comment by chumex412** [comment]
Please indicate that it should be developed with the React email package

**Comment by Saviourise** [comment]
@chumex412 I have done that, please review
