### ISSUE TITLE
[Feature]: Comment page > comment box > implement forwarding of comments within the application

### ISSUE THREAD

**Issue by Uyimolo** [hngprojects/hng_boilerplate_nextjs#160]
### Description

This ticket outlines the creation of a "Forward Button" component specifically designed for enabling users to forward comments to other users within the application.

### Acceptance Criteria
- The component must visually align with the provided Figma design.
- Clicking the forward button initiates a workflow for selecting a recipient.
- Users can search for recipients by username or name using a search bar.
- A dropdown menu suggests relevant recipients based on predefined criteria.
- Users can optionally add a message when forwarding a comment.
- The comment is successfully sent to the selected recipient, including the content and optional message.
- Clear feedback is provided to the user after successful forwarding.
- Authorization checks prevent users from forwarding unauthorized comments.
- Error handling is implemented for various scenarios.
- The component functions efficiently even with a high volume of users and forwarding activity.

### Additional Considerations

- Consider the security implications for forwarding comments and ensure secure data transfer

### Tests

- Ensure the component renders the forward button component
- Test that clicking the forward button initiates the proper workflow for forwarding the comment
- Verify that components successfully sends / forwards the content of the comment (you can mock the api call)
- If optional message field is implemented, test that it functions accordingly
- Test how component handles various error scenarios

![image](https://github.com/user-attachments/assets/f93de9c5-b07a-4467-99e0-7dc362ba6b8b)

### Links

https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=718-11637&m=dev

**Comment by mrcoded** [comment]
Please add more to this issue also include a test case

**Comment by Uyimolo** [comment]
> Please add more to this issue also include a test case

Done sir

**Comment by Uyimolo** [comment]
Too small to be a component
