### ISSUE TITLE
[Feature]: Comments page > comments box > implement like and dislike buttons

### ISSUE THREAD

**Issue by Uyimolo** [hngprojects/hng_boilerplate_nextjs#166]
### Description

This ticket outlines the development of interactive "Like" and "Dislike" buttons for the comment box, allowing users to express their opinions on comments. 

### Acceptance Criteria

**Like Button**
- Must include "Like" button icon (thumbs up icon).
- Must Allow users to like a comment by clicking the button.
- Must Implement functionality to track and display the number of likes a comment receives (like count). 

**Dislike Button**
- Must include "Dislike" button icon (e.g., thumbs down icon).
- Allow users to dislike a comment by clicking the button.
- Implement functionality to track and display the number of dislikes a comment receives (dislike count)

![image](https://github.com/user-attachments/assets/2ef13173-4346-40b6-aba0-c0031d0502b0)
![image](https://github.com/user-attachments/assets/167d19cd-ec9f-4428-8fe4-0615664394af)

### Links

https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=561-26055&m=dev

**Comment by chumex412** [comment]
This is too small a ticket, please let the assignee know they're implementing the whole comment section including the button or remove it entirely.

**Comment by Uyimolo** [comment]
Too small to be a ticket
