### ISSUE TITLE
[FEAT]:  Contact us > Create the Social link UI component

### ISSUE THREAD

**Issue by abel-otegbola** [hngprojects/hng_boilerplate_nextjs#170]
### Description

Develop a social link component that will be used in the the Contact Us page. Ensure the component layout matches the provided design specifications, displays the icons and texts prominently. This component will feature the Contact Us page, developed by another intern, and ensure it functions correctly within the page layout.

### Acceptance Criteria

 Create the Social link component
 Ensure the Social link is displayed correctly within the page layout.
 Ensure the Social link matches the provided design specifications.
 Include props for dynamically adding icon and text content.
 Write unit tests to verify props are rendered correctly.

Image:

![social links](https://github.com/user-attachments/assets/fc8345bd-e06c-4d55-a3e6-484b76c780a2)

### Links

[Figma](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=432-7603&m=dev)

**Comment by mrcoded** [comment]
please add more to this issue @abel-otegbola

**Comment by abel-otegbola** [comment]
Ticket has been merged with #173
