### ISSUE TITLE
[Feature]: SETTINGS PAGE - Implement the Password successful modal

### ISSUE THREAD

**Issue by Ayodejioladimeji** [hngprojects/hng_boilerplate_nextjs#172]
### Description

Implement a modal that appears when a user's password update is successful. 
The modal should include a "Continue" button that, when clicked, disables the modal. 
Additionally, users should be able to click outside the modal to disable it.

### Acceptance Criteria

1. The modal should display a message indicating the password update was successful.
2. The modal should include a "Continue" button that disables the modal when clicked.
3. Clicking outside the modal should also disable it.
4. The modal should be styled according to the provided design specifications.
5. The modal should be responsive across all devices (mobile, tablet, desktop).
6. Unit tests should cover the modal's functionality.
7. Integration tests should ensure the modal works correctly within the settings page.

![Success Message Box](https://github.com/user-attachments/assets/8748b5c2-4e37-467f-ad51-fee4648a90af)

### Links

https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=10-17157&m=dev

**Comment by Maiqel1** [comment]
@oghene-ella, hi
Pls a timeframe wasn't included in this issue

**Comment by oghene-ella** [comment]
Today, 11:59pm… styling - shadcn
You self assigned this issue? @Maiqel1 

you can’t self assign a task.

**Comment by oghene-ella** [comment]
@Maiqel1 go ahead with it…
@Gladchux14 look for another issue to fix

**Comment by Maiqel1** [comment]
@Gladchux14 did you not read the instruction? find something else!
