### ISSUE TITLE
[Feat]: Create the contact us social media links section, FAQ link section

### ISSUE THREAD

**Issue by abel-otegbola** [hngprojects/hng_boilerplate_nextjs#173]
### Description

Develop the social links section and the FAQ link section which are in the Contact Us page. Ensure the section layout matches the provided design specifications, displays the sections prominently. This page will feature the Contact us page, developed by another intern, and ensure it functions correctly within the page layout.

### Acceptance Criteria

- [ ] Create the social links section and ensure it is displayed correctly within the page layout.
- [ ] Add the Heading, text
- [ ] Add the links using the previously created social links components.
- [ ] Create the FAQ shortcut section under the social links section

### Links

[Figma](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=432-7586&m=dev)

### Image
![social links section](https://github.com/user-attachments/assets/38cad137-012c-4b57-ae81-d78804bcb00b)

**Comment by mrcoded** [comment]
this is not good enough, add more to it @abel-otegbola

**Comment by abel-otegbola** [comment]
Joined the #170 ticket with this one
