### ISSUE TITLE
[FEAT] Organization settings  > Roles and permission page > Implement  successfully  created a role modal

### ISSUE THREAD

**Issue by oreoluwa212** [hngprojects/hng_boilerplate_nextjs#178]
## Description
Create the success modal for confirming the creation of a new role.

## **Purpose**
I want to know that the "Create Role" action was successful

## **Requirement**
- Implement a success modal to confirm role creation
- Ensure this modal follow the brand's design guidelines
- Make sure the modal is responsive

## **Testing**
- Test if the success modal displays a tick icon, success text, confirmation message, and "Continue" button
- Test responsiveness of the modal on various device widths

## **Task**
- [ ] Create a success modal with the tick icon, success text, confirmation message, and "Continue" button

### Acceptance Criteria

- On successfully creating a role, a success modal should appear with:
  - A large tick icon for success
  - A "Success" text
  - A message: "You have created your new role successfully!"
  - A "Continue" button
- Both modals adhere to the brand colors and design
- Both modals are responsive across device widths

## **Picture**  
![Success action](https://github.com/user-attachments/assets/7822415d-9676-4e68-b88d-f86d686a19ef)

## **Dev Mode**  
- [Dev Mode Link](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=118-45057&m=dev)

**Comment by Dorcas-BD** [comment]
How do I assign this to myself?

**Comment by oreoluwa212** [comment]
Click assign yourself

**Comment by Meekaylah** [comment]
This ticket is a duplicate.
