### ISSUE TITLE
[FEATURE] 🗺️ ⚙️ Settings Pages > organization Settings > implement copy and refresh dynamic link

### ISSUE THREAD

**Issue by Manlikevee** [hngprojects/hng_boilerplate_nextjs#189]
### **Description**
Develop a component that generates, displays, and allows users to copy and refresh a dynamic referral link. This component should be user-friendly, visually appealing, and provide real-time feedback to the user when the referral link is copied or refreshed.

### Acceptance Criteria

- [ ] The component generates and displays a dynamic referral link.
- [ ] The component includes a button to copy the referral link to the clipboard.
- [ ] The component includes a button to refresh the referral link.
- [ ] Provide real-time feedback to the user when the link is copied or refreshed.
- [ ] Ensure the component is fully responsive and works well on all screen sizes.
- [ ] Check that the component allows users to copy the referral link to the clipboard.
- [ ] Verify that the component generates a new referral link when the refresh button is clicked.

### Links

| [`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=96-25674&t=JlOHEn6aRQ1D8QE2-1)

### Images

![image](![Frame 1000001718](https://github.com/user-attachments/assets/c4c20bc6-8c52-4ca3-ba25-0d7f7da9765c))

**Comment by JulianaSau** [comment]
@Manlikevee 
Make the title of the issue simpler and more straight forward. iF you need the person to know all this settings pages > etc include it under links or something
Update this issue to look more presentable. Include images of the component, 
Are there props that this component should receive? if so document them.
