### ISSUE TITLE
[FEAT] Authentication Page -> Success page for magic link  

### ISSUE THREAD

**Issue by Justfemi** [hngprojects/hng_boilerplate_nextjs#19]
### Description
Implement the successful login with magic link page as shown in the design

### Acceptance Criteria
- Responsive across all screen sizes (desktop, tablet and mobile)
- Write tests for your code.
- Use components where necessary (header, footer, buttons, modal and so on)

### Timeframe
24 hours

[Link to Design](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=2-938&t=p2gECcZQmYqvvrn7-4)

### Preview
![image](https://github.com/user-attachments/assets/9bea3171-0e29-409e-acd7-e7421aa9c086)

**Comment by oyerohabib** [comment]
I am working on this already.
