### ISSUE TITLE
[Feature]: [FEAT] EMAIL TEMPLATES > Implement email verification page WITHOUT image

### ISSUE THREAD

**Issue by crystal4000** [hngprojects/hng_boilerplate_nextjs#195]
### Description

This email is designed to confirm the user's email address during account registration, providing a straightforward method to verify their account.

### Acceptance Criteria

-  The email template is implemented according to the provided design, WITHOUT an image.
-  The template is responsive and displays correctly across various email clients.

### Requirements:

-  Main heading: "Email Verification"
-  Personalized greeting (e.g., "Hi John Doe,")
-  Brief explanation of why they're receiving this email
-  Instructions on how to verify their email
-  Call-to-action button for email verification
-  Alternative verification link
-  Expiration notice for the verification link
-  Sign-off and company name

### Tests:

-  Ensure all elements render correctly and match the design.
-  Verify responsiveness across various email clients and device sizes.
-  Check that personalization fields populate correctly.
-  Test the functionality of the Verify Account button.
-  Verify the alternative verification link is correct and functional.

### Tasks:

-  Develop the Email Verification Template based on the provided design and requirements.
-  Implement a responsive layout that works well across different email clients.
-  Set up personalization fields for the recipient's name.
-  Implement the Verify Account button with proper styling and linking.
-  Include an alternative text-based verification link.
-  Add a clear expiration notice for the verification link.
-  Ensure all text content is editable for easy customization.
-  Implement tracking parameters for the verification button and link (if applicable).
-  Add a note for users to ignore the email if they didn't request it.

### Links

| [`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=402-48128&t=dna4j6vXC0PrBW0R-0)

### Images

<img width="276" alt="image" src="https://github.com/user-attachments/assets/0b06ca72-15d0-4b4e-a28e-72cdcf93b9e2">

**Comment by chumex412** [comment]
Issue #196 and this should be one ticket

**Comment by chumex412** [comment]
Also, edit the description to include React email package useage for email templates.
