### ISSUE TITLE
[Feature]: [FEAT] EMAIL TEMPLATES > Implement email confirmed page

### ISSUE THREAD

**Issue by crystal4000** [hngprojects/hng_boilerplate_nextjs#197]
### Description

This email is designed to confirm that a user's email has been successfully verified and highlight the key features and benefits of the Boilerplate service.

### Acceptance Criteria

- The email template is implemented according to the provided design, **including an image**.
- The template is responsive and displays correctly across various email clients.
- Create with React Email

### Requirements

The email template should include the following elements:

- Main heading: "Email Confirmed"
- Subheading: "Your email has been verified"
- Personalized greeting (e.g., "Hi John Doe,")
- Confirmation message and brief product description
- Section highlighting key features and benefits
- Call-to-action button
- Sign-off and company name

### Tests

- Ensure all elements render correctly and match the design.
- Verify responsiveness across various email clients and device sizes.
- Check that personalization fields populate correctly.
- Test the functionality of the CTA button.

### Tasks

- Develop the Email Confirmation Template based on the provided design and requirements.
- Implement a responsive layout that works well across different email clients.
- Set up personalization fields for the recipient's name.
- Implement the CTA button with proper styling and linking.
- Ensure all text content is editable for easy customization.
- Implement tracking parameters for the CTA button (if applicable).

### Links

| [`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=67-38271&t=oGYpLbnVcfOnd2oi-0)

### Images

<img width="253" alt="image" src="https://github.com/user-attachments/assets/c305c586-aaad-4247-8050-37dcc4505749">

**Comment by CodeDeveloper19** [comment]
Hello..please I have a question concerning this feature, I see three different email confirm pages with different images. Should I choose one for myself? Or am I to implement the desktop and mobile for the three email confirm pages with these different images?

**Comment by crystal4000** [comment]
Implement the design that is selected when you click on the figma link. The one you are creating is the one with the green success icon/image. Implement the desktop and mobile for that please.

![image](https://github.com/user-attachments/assets/10f03f1d-a081-4d05-9f04-abd96d3c8005)

**Comment by chumex412** [comment]
@crystal4000 update your description to let interns know they should use React email.
