### ISSUE TITLE
[Feature]: [FEAT] User Dashboard Product Details Page

### ISSUE THREAD

**Issue by crystal4000** [hngprojects/hng_boilerplate_nextjs#204]
### Description

Develop a Product Details Page component for the User Dashboard. This component displays detailed information about a selected product alongside the product list, allowing users to view and manage individual product information efficiently.

### Acceptance Criteria

- The component is implemented according to the provided design, integrating seamlessly with the existing Product Lists Component.
- The layout is responsive and displays correctly across various device sizes.

### Requirements:

- Product image
- Product name as the header
- Close button to dismiss the details view
- Product information fields: Product ID, Category, Date added, Stock, Price
- Product description
- Edit and Delete buttons

### Tests:

- Ensure the component renders correctly when a product is selected from the list.
- Verify that all product details are displayed accurately.
- Test the close button functionality to dismiss the details view.
- Check that the product image loads correctly and is responsive.
- Verify that the Edit and Delete buttons are functional (if implemented).
- Ensure the component integrates well with the existing Product Lists Component.
- Test the responsiveness of the layout on different screen sizes.

### Tasks:

- Develop the Product Details Page component based on the provided design and requirements.
- Implement a responsive layout that adapts to different screen sizes and integrates with the Product Lists Component.
- Create the header with the product name and close button.
- Add a section for displaying the product image.
- Implement fields for showing product details (ID, Category, Date added, Stock, Price).
- Create a section for the product description.
- Add Edit and Delete buttons with appropriate styling.
- Ensure the component can receive and display data for the selected product.
- Implement the close functionality to dismiss the details view.
- Add appropriate alt text for the product image and aria labels for accessibility.
- Optimize image loading for performance.
- Implement error handling for cases where product data might be incomplete or unavailable.
- Create smooth transitions for opening and closing the details view.
- Ensure all text is properly formatted and truncated if necessary to fit the layout.
- Implement the Edit and Delete functionalities (or prepare them for future implementation).

### Timeframe
**Deadline: Saturday @ 1pm**

### Task(s) Linked to this feature

- [User Dashboard Product Details Component](https://github.com/hngprojects/hng_boilerplate_nextjs/issues/206)

### Links

| [`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=771-9673&t=qmayD95LoQU8WeUi-4)

### Images

<img width="514" alt="image" src="https://github.com/user-attachments/assets/0f2f35c0-55b7-4938-920c-b6ee6b37b0e3">

**Comment by kleenpulse** [comment]
Done PR => https://github.com/hngprojects/hng_boilerplate_nextjs/pull/490
