### ISSUE TITLE
[Feature]: Email Templates > SuperAdmin Email Management Dashboard >HTML Template Editor Block Component

### ISSUE THREAD

**Issue by elitenoire** [hngprojects/hng_boilerplate_nextjs#205]
### Description

Create Reusable Template Editor Block Component that supports copy html content, delete block, move block upwards or downwards.

### Acceptance Criteria

- [x] Make Editor Block Component reusable
- [x] Responsive and adheres to brand colors and design
- [x] Component accepts children
- [x] Implement active and inactive states of Template Editor Block
	- [x] Inactive state is the default state of the Block
	- [x] Clicking on a Block toggles to active state while inactive
	- [x] Clicking outside the Block toggles to inactive  while in active state
	- [x] In active state, Block component is highlighted and a visible toolbar is shown
- [x] Implement Toolbar component using [Radix Toolbar](https://www.radix-ui.com/primitives/docs/components/toolbar)
- [x] Toolbar Upwards Icon button using arrow-up icon
- [x] Toolbar Downwards Icon button using arrow-down Icon
- [x] Toolbar Copy Icon button using copy icon
- [x] Toolbar Delete Icon button using delete icon
- [x] Icons are from already installed lucide-react icon library
- [x] Implement copy functionality
- [x] Read from downwards, upwards and delete functionality from Editor Context via hook
	- [x] Attach the functionalities to the Toolbar Downwards, Upwards and Delete buttons

### Related Components
Components are closely linked together and devs should ensure the components work together
- #185
- #219

### Deadline
You are given till Saturday 20th July 11:00AM WAT to complete the task.

### Links

| [`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=900-14320&m=dev)

### Images

![editor_block](https://github.com/user-attachments/assets/12b68e10-876e-4ee6-a453-9b4ba5a1a36e)
![editor_block_unselected](https://github.com/user-attachments/assets/4ea215d8-c3f7-4c4f-83af-88e8aa04d2fe)
![editor_block_active](https://github.com/user-attachments/assets/bade7178-e1a3-4697-aa14-01e0a40ece33)

**Comment by archwin010** [comment]
i own this ticket
