### ISSUE TITLE
[Feature]: Notification Card Component

### ISSUE THREAD

**Issue by prudentbird** [hngprojects/hng_boilerplate_nextjs#217]
### Description

Implement a notification card components that can dynamically display various notifications as props. Ensure the component follows the specified design guidelines and is responsive across device widths.

### Acceptance Criteria

- The notification card should display the title, number of unreads, push notifcations button, notifcation previews, and a call to action.
- The contents of the notification card should be dynamic and passed as props.
- Inactive call to action when count of unread messages === 0
- The notification card should have a consistent layout across different screen sizes.
- The notification card should adhere to the brand colors and design.
- The notification card should be responsive across device widths.

### Props
- Count of unread messages
- Notification preview ( header and time )

### Expected Outcome
- Users should be able to view the notification card with all relevant information.
- The notification card content should be dynamic and change based on the props passed to it.
- The notification card should be responsive and adjust its layout based on the device width.

### Purpose
Render various notifications dynamically in a consistent and responsive format as a reusable notification card component.

### Links

| [`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=2179-42619&t=qxQa0CBjPBDDEcMX-1)

### Images
![Notification Card](https://github.com/user-attachments/assets/86de5c52-67b5-4952-9c71-28cfcafe78d4)

### Testing

- [ ] Test if the notification card displays correctly with the dynamic content passed as props.
- [ ] Test if the notification card displays the title, number of unreads, push notifcations button, notifcation previews, and a call to action.
- [ ] Test if the notification card follows the brand colors and design.
- [ ] Test the responsiveness of the notification card on various device widths.

**Comment by kelani34** [comment]
You did not list the needed props or give an idea of what should be passed.

**Comment by Codegirlemem** [comment]
This ticket has been taken by me, Codegirlemem. Please no one should unassign me to assign themselves to this.

Let's be matured please. Thanks

**Comment by Codegirlemem** [comment]
@PrudentBird what should be displayed in the place where the preview messages are when there are no notifications? should the place just be empty like that? with just the inactive cta button?

**Comment by prudentbird** [comment]
@Codegirlemem yes, it should be empty and the count should be you have 0 unread messages.

In your test, simulate with mock data for the different render cases when there are notifications and there are no notifications!
