### ISSUE TITLE
[Feature]: Organization settings  > Roles and permission page > Implement roles sidebar

### ISSUE THREAD

**Issue by luqmonac56** [hngprojects/hng_boilerplate_nextjs#228]
### Description
Create the "roles side bar" on the roles and permissions page.

### Expected Outcome

1. User should be able to click on different roles to edit their permissions

### Purpose
As a user, I want to set permissions for different  roles therefore make the menus clickable

### Requirement

1. Implement the sidebar as described in the design
2. Ensure the sidebar follows the brand's design guidelines
3. Make sure the sidebar is responsive according to design 

### Testing

1. Test if the menus on the sidebar shows the expected permissions when clicked

### Task

1.  Create the sidebar component
2.  Ensure the sidebar follows the design
4.  Ensure the sidebar is responsive according to design

### Acceptance Criteria

1. Sidebar menus are clickable
2. Sidebar adheres to the design
3. Sidebar is responsive across all screen sizes according to design

### Links
[Figma link](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=118-44402&m=dev)

### Image

![Frame 1618873044](https://github.com/user-attachments/assets/a31cfddc-4e35-46ae-87e2-9eef1c3646a0)

**Comment by techbycornel** [comment]
I'm here

**Comment by OSKIconcept** [comment]
@chumex412 please when is the deadline for this ?

**Comment by chumex412** [comment]
You shouldn't be asking me this @OSKIconcept, @luqmonac56 should be in the best position to answer this.
