### ISSUE TITLE
[FEAT] - User Dashboard Settings Side nav

### ISSUE THREAD

**Issue by SirhmVFX** [hngprojects/hng_boilerplate_nextjs#231]
### Description:

Implement the User Dashboard Settings Side nav. The Nav Bar should adhere strictly to the design specifications provided. Below are the detailed instructions and requirements.

**Requirements:**

1. **UI Components:**
   - Use ShadCN UI components for consistency.
   - Ensure components match the design specifications provided.

2. **Design Specifications:**
   - Refer to the provided design for dimensions, colors, and layout.
   - Include all navigation tabs and drop down as designed.

3. **Functionality:**
   - Make sure all navigation tabs route to their specified pages 

4. **Accessibility:**
   - Ensure components is accessible and follow best practices 

5. **Testing:**
   - Ensure the component renders correctly with all required elements.

**Deadline: Friday 4pm** 
    
**Acceptance Criteria:**

- [ ] The `UserDashboardSettingsSideNavBar` component is created and located in the `components` directory.
- [ ] The Side Nav Bar matches the design specifications.
- [ ] The Side Nav Bar functions correctly and includes all items as per the design.
- [ ] Components are accessible and follow best practices.

**Attachments:**
![Screenshot 2024-07-18 at 17 55 46](https://github.com/user-attachments/assets/9ecf113d-4fb9-4cf6-ab88-06900699fb18)

[Link to Design File](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=2179-37386&m=dev)

- [ShadCN UI Documentation](https://ui.shadcn.com/)

**Comment by incredible-phoenix246** [comment]
@OSKIconcept this issues has been closed already

**Comment by phoenixdahdev** [comment]
@ickynavigator 
https://github.com/hngprojects/hng_boilerplate_nextjs/pull/239

**Comment by phoenixdahdev** [comment]
This ticket has been taken

**Comment by Petersonbabs** [comment]
Buth there's no assignee on it currently.

**Comment by Pamode-Ukwe** [comment]
Why are people assigning and unassigning?

**Comment by Petersonbabs** [comment]
I'm wondering too. Before I assign it to myself...  May someone was already working on it

**Comment by Lucky-tech10** [comment]
I want to assign this issue to myself

**Comment by denovan6k** [comment]
Lol what's going on here?
