### ISSUE TITLE
[FEATURE] 🗺️ User Dashboard & Products Pages > Dashboard > implement a reusable  Currency Formatter component

### ISSUE THREAD

**Issue by Manlikevee** [hngprojects/hng_boilerplate_nextjs#26]
- https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=4-49804&t=ybfmYNMB6xh8HxXT-1

### **Description**
Develop a reusable Currency Formatter component. This component will be used to format and display currency values across the website. The Currency Formatter should be accurate, versatile, and adhere to international currency standards. It should include the following features:

Acceptance Criteria

The Currency Formatter component is implemented according to the design.
The component should correctly format currency values for different currencies.
Ensure accessibility standards are met, including appropriate labeling for screen readers.
The component should handle edge cases such as large values, negative numbers, and zero values.
Requirements

The component should receive the following props:

1. amount: The numerical value to be formatted.
2. currency: The currency code (e.g., "USD", "EUR", "JPY").
3. showSymbol: A boolean to determine whether to display the currency symbol.

Tasks

- [ ] Develop the Currency Formatter component based on the provided requirements.
- [ ] Implement currency code handling.
- [ ] Ensure the component renders correctly with various currency values.
- [ ] Check that the component handles different currency codes.
- [ ] Test the component with edge cases like large values, negative numbers, and zero.
- [ ] Ensure proper handling of edge cases.
- [ ] test for cases where value is null, symbol is null, or value is a string
- [ ] Test the component for accuracy and access
![Data Card (1)](https://github.com/user-attachments/assets/5b377762-5068-4cce-a460-98e1dbf1a82f)

**Comment by Codegirlemem** [comment]
@Amdragz you already unassigned yourself this ticket so I have assigned myself to it.

**Comment by Amdragz** [comment]
@Codegirlemem I didn't unassign myself, please if it was unassigned , it probably would have been a mistake

**Comment by Amdragz** [comment]
I am assigned to this ticket, if it was seen as unassigned then that was a
mistake

**Comment by Codegirlemem** [comment]
@Amdragz but the log says you unassigned yourself and i worked with that
