### ISSUE TITLE
[FEAT] Organization settings > Manage Members >Implement the page

### ISSUE THREAD

**Issue by luqmonac56** [hngprojects/hng_boilerplate_nextjs#52]
### Description
Implement the the members page to allow the user manage members

### Acceptance Criteria

1. The page is implemented according to the design
2.  Import and use the necessary reusable components.
3. Error messages should be displayed for invalid inputs.
4. Write a unit test for this page.
5. The page should be responsive across all screen sizes.

### Tasks
- [ ] Implement the the members  page and make it responsive  across all screen sizes.
- [ ] Write a unit test for this page.

[Link to the figma file](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=96-19490&m=dev)

## Dependent Component Issue Link
[Link to Sidebar](https://github.com/hngprojects/hng_boilerplate_nextjs/issues/28)
[Link to Delete Modal](https://github.com/hngprojects/hng_boilerplate_nextjs/issues/181)

### Picture of the corresponding page of the ticket from the Figma:
![Inactive Invite](https://github.com/user-attachments/assets/05e2d7bc-d859-4090-9f53-d715e385b92f)

## Deadline 
 - Friday, 10am

**Comment by SilverBeing** [comment]
This task is dependent on #34 #25 #14 #44

**Comment by Maryanne27** [comment]
Hi @Samadeen @luqmonac56 @ickynavigator please whats the deadline for this issue
