### ISSUE TITLE
[FEAT] External static Page > Sub Page Hero Component

### ISSUE THREAD

**Issue by taiwonaf** [hngprojects/hng_boilerplate_nextjs#56]
# **Description**
Implement both the mobile and web view of the static pages sub pages hero section. This section should be reusable accepts props of page title and page description.

# **Acceptance Criteria**
- Pixel perfect implementaiton
- Responsive implementation
- Clean code
- Make use of reusable components where needed, make one if needed
- Follow the [contribution guidelines](https://github.com/hngprojects/hng_boilerplate_nextjs/blob/0acf613964ea064ae211a91d0a74d13938e4bc23/CONTRIBUTING.md) and [code of conduct](https://github.com/hngprojects/hng_boilerplate_nextjs/blob/0acf613964ea064ae211a91d0a74d13938e4bc23/CODE_OF_CONDUCT.md)

# **Requirements**
- Make a reusable component that accpets props
- Heading prop is required
- Description prop is required

# **Testing**
- Write test to ensure the page renders the required contents

# **Deadline**
Friday 11:59 pm WAT

# **Tasks**
- [ ] Implement all the sections in the design
- [ ] Responsiveness across all screens
- [ ] Make use of reusable components where needed
- [ ] Write test for the implementations
- [ ] Proper commit message

# **Images**
![Hero](https://github.com/user-attachments/assets/389a1612-cf23-492c-b409-989cbcab9890)

[Figma design](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=2349-12237&m=dev)

**Comment by PrimoCrypt** [comment]
Assigned!

**Comment by leothatguy** [comment]
Assigned!

**Comment by Emmanuel-Xs** [comment]
Hey @PrimoCrypt how's it going with your component, it is way pass your deadline. I need your component to submit

**Comment by leothatguy** [comment]
I submitted a PR yesterday #279

**Comment by Emmanuel-Xs** [comment]
okay

**Comment by leothatguy** [comment]
#341

**Comment by Emmanuel-Xs** [comment]
please follow up with your pr, make sure it is up to date

**Comment by Emmanuel-Xs** [comment]
hey whats up, follow up with your pr please

**Comment by harjibbolar26** [comment]
Honestly this is the only component left and I can't trace the person via slack... Bro we're waiting... Pull up please

**Comment by leothatguy** [comment]
I have made pull request I have tagged Oreee in the group but she isn't merging still, I have made another PR still but no reponse...you guys should tag and tell them to check #341

**Comment by harjibbolar26** [comment]
Alright bro.. please keep checking up with her 👍🏾

**Comment by harjibbolar26** [comment]
Bro you added 70% opacity to the black background colour which shouldn't be. It's not pixel perfecting our work.
Please work on it and make another PR

**Comment by harjibbolar26** [comment]
If other components would require it, some of us do not need it in our page.. so try to make the opacity a props so whoever is using it can set it to whatever they want. Abegg

**Comment by Emmanuel-Xs** [comment]
yeah, you did us dirty here ooh 
![image](https://github.com/user-attachments/assets/337940d3-7ab9-4a56-9ec7-c249de4e2113)
![image](https://github.com/user-attachments/assets/3538ced6-a970-431c-b66f-2ada70871229)

**Comment by leothatguy** [comment]
@harjibbolar26 I guess your work has a background color of #444 on the figma...the opacity used is 70%. It's the figma background that has a the #444 hex code beneath that's why it looks that way.
Try adding bf color of #444 to see

**Comment by Emmanuel-Xs** [comment]
best add a className prop you can pass to the parent div, use cn function from ~/lib/utils to marge the tailwindcss classes

**Comment by leothatguy** [comment]
What's your name on slack? @Emmanuel-Xs

**Comment by harjibbolar26** [comment]
@PrimoCrypt you guessed wrong sir.
I don't want to add any hard coded colour. 
You're working on a component that would be used by a whole lot of people so things like background colour should have been passed as a prop, the same way you passed the text

**Comment by Emmanuel-Xs** [comment]
it is @Xs, @PrimoCrypt

**Comment by leothatguy** [comment]
Check dm

**Comment by Emmanuel-Xs** [comment]
okay

**Comment by harjibbolar26** [comment]
@PrimoCrypt drop your slack username too.. I don find you tire

**Comment by leothatguy** [comment]
@RhythmicDevLeo

**Comment by harjibbolar26** [comment]
I'm coming for you boss 🫵🏾🫵🏾
