### ISSUE TITLE
[FEAT] External static page > Breadcrumb component

### ISSUE THREAD

**Issue by taiwonaf** [hngprojects/hng_boilerplate_nextjs#59]
# **Description**
Implement a reusable breadcrumb components that accets pages with the pages name and links also specifying the current page. The current page should appear 
inactive and not clickable and should be the last.

# **Acceptance Criteria**
- Pixel perfect implementaiton
- Responsive implementation
- Clean code
- Make use of reusable components where needed, make one if needed
- Follow the [contribution guidelines](https://github.com/hngprojects/hng_boilerplate_nextjs/blob/0acf613964ea064ae211a91d0a74d13938e4bc23/CONTRIBUTING.md) and [code of conduct](https://github.com/hngprojects/hng_boilerplate_nextjs/blob/0acf613964ea064ae211a91d0a74d13938e4bc23/CODE_OF_CONDUCT.md)

# **Requirements**
- Make a reusable component that accpets props
- show all the pages in order of the url
- Specify the current page with an inactive styling
- Other pages should be clickable

# **Testing**
- Write test to ensure the page renders the required contents

# **Deadline**
Friday 2:00 pm WAT

# **Tasks**
- [ ] Implement all the sections in the design
- [ ] Responsiveness across all screens
- [ ] Make use of reusable components where needed
- [ ] Write test for the implementations
- [ ] Proper commit message

# **Images**
![Breadcrumb](https://github.com/user-attachments/assets/0d41507b-fcfb-463b-a247-b6980659cdf7)

[Figma design](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=4-24185&m=dev)

**Comment by kingbary** [comment]
Hello @elitenoire, are you done with this?

**Comment by elitenoire** [comment]
> Hello @elitenoire, are you done with this?

Yes. I am awaiting #262 to be merged

**Comment by Emmanuel-Xs** [comment]
please try making your code up to date to avoid conflict, from the nextjs boiler repo

**Comment by Emmanuel-Xs** [comment]
Have you a made a pr for your new changes

**Comment by elitenoire** [comment]
@Emmanuel-Xs Yes, new PR made.

**Comment by Emmanuel-Xs** [comment]
nice, thanks

**Comment by Emmanuel-Xs** [comment]
just be following it especially when upstream branch is update

**Comment by Emmanuel-Xs** [comment]
well done
