### ISSUE TITLE
[FEATURE] Implement Filter button component

### ISSUE THREAD

**Issue by judeb21** [hngprojects/hng_boilerplate_nextjs#60]
## Description
Develop a Filter button component that will be used across the Admin product listing page. The filter component will filter all product listings by the parameters passed to it. 

## Acceptance Criteria

- The Filter Component must be implemented accordingly with the design
- Ensure the Component is mobile responsive
- Ensure the component renders what is expected
- Write test for the component

## Requirement

- [ ] The component must be implemented according to the design.
- [ ]  Must filter product lists by given parameters
- [ ] The component must drop down list of filter terms

### Test Script

- Ensure filter component drop downs filter terms
- Ensure filter component actually emits the filtered parameters
- Test component for accessibility and responsiveness

## Link
[Figma](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=528-22080&m=dev)

### Image

<img width="123" alt="Screenshot 2024-07-18 at 09 26 53" src="https://github.com/user-attachments/assets/c5b5404b-1e47-48c5-80f7-92e281605a31">

<img width="76" alt="Screenshot 2024-07-18 at 09 27 15" src="https://github.com/user-attachments/assets/19c18895-e176-4454-8ddb-233ac9bde0a2">

**Comment by Samadeen** [comment]
Can you kindly provide more information and maybe an image of what the filter should look like?

**Comment by judeb21** [comment]
@Samadeen Image added, thanks

**Comment by Uyimolo** [comment]
> @Samadeen Image added, thanks

The second image you added, doesn't relate to the issue, check the design its been updated. Please remove the second image and add the new filter and dropdown image. Thanks.
