### ISSUE TITLE
[FEAT] External Dynamic Pages -> Blog Post Page -> Implement Related Articles

### ISSUE THREAD

**Issue by kleenpulse** [hngprojects/hng_boilerplate_nextjs#76]
## Description
Develop a reusable Related Articles component. This component will be used to display related articles on individual blog post pages. The Related Articles component should include the following elements:

## Acceptance Criteria

- The Related Articles component is implemented according to the design.
- The component should be fully responsive and look good on all screen sizes.

### Requirements	
The component should receive the following props:

- List of related articles (each article includes title, description, date, author name, reading time, tag, and image)

### Testing

- Ensure the component renders correctly with all required elements.
- The current Blog post shouldn't be included included in related
- Check that the component handles edge cases (e.g. overflows)

### 
Tasks

- [ ] Develop the Related Articles component based on the provided requirements.
- [ ] Run tests to ensure the component works as expected
- [ ] Test the component for responsiveness and accessibility.

# LINKS

[`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=645-38630&m=dev).

# IMAGES

![image](https://github.com/user-attachments/assets/9833a38a-903c-41f2-b223-67f11643a892)

**Comment by kingstech001** [comment]
please check this figma link I don't think it is the correct one

**Comment by jerahmeel200** [comment]
the design on the figma is not clear

**Comment by kingstech001** [comment]
The link to the figma is not correct I was searching for the section I'm
supposed to work on but is it not there, it is  on another issues figma

**Comment by kleenpulse** [comment]
@kingstech001 fixed

**Comment by erasmusedwardobeth** [comment]
@kleenpulse 
Mobile version is not corresponding to Desktop version on figma link
am not even sure if they mean the same thing
heading and images are different it was likely an oversight on the designer
but will definitely cause trouble for me if I implement two different designs that are supposed to show a single design responsiveness 
please add an image of it the mobile design am implementing to the issue!!
