### ISSUE TITLE
[FEAT] Super Admin Dashboard Page

### ISSUE THREAD

**Issue by SirhmVFX** [hngprojects/hng_boilerplate_nextjs#78]
### Description:
---

Using existing implemented components, Implement the Super Admin Dashboard ensuring consistency with ShadCN UI components. The Admin Dashboard should adhere strictly to the design specifications provided. Below are the detailed instructions and requirements.

**Requirements:**

1. **UI Components:**
   - Use existing card, charts and products components for consistency.
   - Ensure all components match the design specifications provided.

2. **Design Specifications:**
   - Refer to the provided design for dimensions, colors, and layout.
   - Include all items and interactions as designed

3. **Functionality:**
   - put together all existing components to make up the admin dashboard page

4. **Accessibility:**
   - Ensure all components are accessible and follow best practices

5. **Testing:**
   - Ensure the component renders correctly with all required elements.

**Acceptance Criteria:**

- [x] Ui Should be pixel perfect as implemented using ShadCN UI.
- [x] All components are accessible and follow best practices.

**Attachments:**
![Screenshot 2024-07-17 at 16 06 45](https://github.com/user-attachments/assets/985ad8f6-68c5-479d-b6b9-be60b7824ae9)
[Link to design file](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=176-53357&m=dev)

- [ShadCN UI Documentation](https://ui.shadcn.com/)

**Comment by chumex412** [comment]
Provide links to the ShadCN components need for page
