### ISSUE TITLE
[FEAT] External Dynamic Pages >Career Page > create the career card component

### ISSUE THREAD

**Issue by kleenpulse** [hngprojects/hng_boilerplate_nextjs#88]
## Description
Develop a reusable career card component to display individual job listings on the Career Page. This component should present key job information in a clear, attractive, and consistent format.

## Acceptance Criteria

- The career card component accurately summarizes all required job information.
- The design is responsive and maintains visual consistency across different screen sizes.
- The component includes interactive elements that function correctly.

### Requirements	
The career card should include the following elements:
- Company location
- Tags for job type (e.g., "Remote") and department
- Brief job description or responsibilities
- Salary range
- "View details" button

### Tests

- Verify that the component renders correctly with all required information.
- Test the responsiveness of the card across various device sizes.
- Ensure the "View details" button functions as expected.
- Check that long text (e.g., job titles or descriptions) is handled appropriately.

###  Tasks

- Design the career card component based on the provided example and requirements.
- Implement the component structure using semantic HTML.
- Create props or data structure to populate the card with dynamic content.
- Add hover and focus states for interactive elements.
- Implement loading states or skeletons for when data is being fetched.

# LINKS

[`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=1666-52483&m=dev).

# IMAGES

![image](https://github.com/user-attachments/assets/61a56860-9130-4cfb-9162-b5ba1ee4cd8b)

**Comment by EniolaCodes** [comment]
I would like this issue to be assigned to me.

**Comment by kleenpulse** [comment]
whomever is working on this should make sure to use shadcn and tailwind, DO NOT USE ANY OTHER UI LIB @YeeshaDev @EniolaCodes

**Comment by EniolaCodes** [comment]
Can two of us work on the same issue? @kleenpulse

**Comment by YeeshaDev** [comment]
Noted

**Comment by kleenpulse** [comment]
This can be handled by one dev

**Comment by YeeshaDev** [comment]
I don’t think so but I already assigned this to myself

**Comment by EniolaCodes** [comment]
I commented on it first, it should be given to me.

**Comment by YeeshaDev** [comment]
Sorry but We were told to assign not comment

**Comment by kleenpulse** [comment]
@YeeshaDev  Note: other devs need this component for their task, this should be done by 9pm, or I'll assign it to someone else

**Comment by YeeshaDev** [comment]
Please give me till 10pm please I will start it as soon as I get home.
Thanks🙏

**Comment by YeeshaDev** [comment]
@kleenpulse please i cannot find the figma design on the link you added in the comment. i checked the external dynamic page folder on figma

**Comment by kleenpulse** [comment]
@YeeshaDev fixed
