### ISSUE TITLE
[FEAT] Pagination Component

### ISSUE THREAD

**Issue by SirhmVFX** [hngprojects/hng_boilerplate_nextjs#90]
### Description:
---

Implement the pagination components ensuring consistency with ShadCN UI components. This component should adhere strictly to the design specifications provided. Below are the detailed instructions and requirements.

**Requirements:**

1. **Page Components:**
   - Ensure the components match the design specifications provided.

2. **Design Specifications:**
   - Refer to the provided design for dimensions, colors, and layout.

3. **Functionality:**
   - make sure it responds to interaction 

4. **Accessibility:**
   - Ensure the components is accessible and follow best practices

5. **Testing:**
   - Ensure the component renders correctly with all required elements.

**Acceptance Criteria:**

- [ ] Component Should be pixel perfect as implemented using ShadCN UI.
- [ ] Implement interactions with the component 

**Attachments:**
![Screenshot 2024-07-17 at 16 45 09](https://github.com/user-attachments/assets/0d817a73-06f7-4788-b6de-19e7b99901ef)

[Link to the design file](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=2179-37744&m=dev)

- [ShadCN UI Documentation](https://ui.shadcn.com/)

**Comment by Meekaylah** [comment]
This is a duplicate. Please check with the creator of this ticket and create a new one:
https://github.com/hngprojects/hng_boilerplate_nextjs/issues/97
