### ISSUE TITLE
[FEATURE] Create Pagination Component on User Dashboard Product Listing Page

### ISSUE THREAD

**Issue by judeb21** [hngprojects/hng_boilerplate_nextjs#97]
## Description
Create a pagination component, allowing users to view next or previous product listings. This component will view pages based on the user clicks, if the user clicks next they should see the next product listing and if user clicks previous they should see the previous product listing etc.

## Acceptance Criteria

- This pagination component is implemented according to the design. [Use this as guideline](https://ui.shadcn.com/docs/components/pagination)
- The pagination component must be clickable and access the pages accordingly
- Component must be fully responsive and function properly

### Requirements
**The pagination component must accept the following as props**

- Next page
- Previous page
- Page numbers, which are also clickable and function accordingly

### Test Script

- Ensure component is fully responsive
- Ensure component renders it's elements appropriately 
- Ensure each paginated button or link functions appropriately

### Link
[Pagination component](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=528-22082&m=dev)

**Comment by Meekaylah** [comment]
This is a duplicate. Please check with the creator of this ticket and try to create a new one:
https://github.com/hngprojects/hng_boilerplate_nextjs/issues/90
